"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Settings, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { toast } from "sonner";

export type NumberSeriesPopoverProps = {
  /** Module key matching the NumberSeries.module column (e.g. "quote",
   *  "salesOrder", "invoice"). */
  module: string;
  /** Current displayed next-number string (e.g. "QT-00001"). */
  current: string;
  /** Initial fields from the NumberSeries row. */
  prefix: string;
  nextValue: number;
  padding: number;
  isAutoGenerated: boolean;
  /** Server action that persists the change. */
  action: (input: {
    module: string;
    prefix: string;
    nextValue: number;
    padding: number;
    isAutoGenerated: boolean;
  }) => Promise<{ ok: boolean; preview: string }>;
};

/**
 * Settings-gear popover next to the Quote#/Invoice#/SalesOrder# display
 * on transaction forms. Per <quotes_spec>:
 *
 *   "Quote#* — read-only display of next number from
 *    getNextDocumentNumber('QUOTE'), with a settings-gear icon that
 *    opens a popover: 'Auto-generate / Enter manually' radio +
 *    prefix/next number/padding inputs (writes to
 *    TransactionNumberSeries). Default auto-generate."
 */
export function NumberSeriesPopover({
  module,
  current,
  prefix: initialPrefix,
  nextValue: initialNext,
  padding: initialPadding,
  isAutoGenerated: initialAuto,
  action,
}: NumberSeriesPopoverProps) {
  const router = useRouter();
  const [open, setOpen] = React.useState(false);
  const [busy, setBusy] = React.useState(false);
  const [prefix, setPrefix] = React.useState(initialPrefix);
  const [nextValue, setNextValue] = React.useState(String(initialNext));
  const [padding, setPadding] = React.useState(String(initialPadding));
  const [isAuto, setIsAuto] = React.useState(initialAuto);

  // Live preview of what the next number will look like after save.
  const preview = React.useMemo(() => {
    const n = Number(nextValue) || 1;
    const p = Math.min(10, Math.max(1, Number(padding) || 5));
    return `${prefix}${String(n).padStart(p, "0")}`;
  }, [prefix, nextValue, padding]);

  async function submit() {
    if (!prefix.trim()) {
      toast.error("Prefix is required");
      return;
    }
    setBusy(true);
    try {
      await action({
        module,
        prefix: prefix.trim(),
        nextValue: Number(nextValue) || 1,
        padding: Number(padding) || 5,
        isAutoGenerated: isAuto,
      });
      toast.success("Number series updated");
      setOpen(false);
      router.refresh();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Save failed");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="flex items-center gap-2">
      <Input value={current} disabled className="font-mono flex-1" />
      <Popover open={open} onOpenChange={setOpen}>
        <PopoverTrigger asChild>
          <Button
            type="button"
            variant="outline"
            size="icon"
            aria-label="Configure number series"
          >
            <Settings className="h-4 w-4" />
          </Button>
        </PopoverTrigger>
        <PopoverContent className="w-80 space-y-3" align="end">
          <div className="space-y-2 text-sm">
            <p className="font-semibold">Document number</p>
            <fieldset className="space-y-1">
              <label className="flex items-center gap-2">
                <input
                  type="radio"
                  checked={isAuto}
                  onChange={() => setIsAuto(true)}
                />
                Auto-generate
              </label>
              <label className="flex items-center gap-2">
                <input
                  type="radio"
                  checked={!isAuto}
                  onChange={() => setIsAuto(false)}
                />
                Enter manually
              </label>
            </fieldset>
          </div>
          <div className="grid gap-2">
            <div className="space-y-1">
              <Label htmlFor="prefix">Prefix</Label>
              <Input
                id="prefix"
                value={prefix}
                onChange={(e) => setPrefix(e.target.value)}
                disabled={busy}
                maxLength={20}
              />
            </div>
            <div className="grid grid-cols-2 gap-2">
              <div className="space-y-1">
                <Label htmlFor="nextValue">Next number</Label>
                <Input
                  id="nextValue"
                  inputMode="numeric"
                  value={nextValue}
                  onChange={(e) => setNextValue(e.target.value)}
                  disabled={busy}
                />
              </div>
              <div className="space-y-1">
                <Label htmlFor="padding">Padding</Label>
                <Input
                  id="padding"
                  inputMode="numeric"
                  value={padding}
                  onChange={(e) => setPadding(e.target.value)}
                  disabled={busy}
                />
              </div>
            </div>
            <p className="text-xs text-muted-foreground">
              Preview: <span className="font-mono">{preview}</span>
            </p>
          </div>
          <div className="flex justify-end gap-2 pt-1">
            <Button
              type="button"
              variant="ghost"
              size="sm"
              onClick={() => setOpen(false)}
              disabled={busy}
            >
              Cancel
            </Button>
            <Button
              type="button"
              size="sm"
              onClick={submit}
              disabled={busy}
              className="gap-1"
            >
              {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
              Save
            </Button>
          </div>
        </PopoverContent>
      </Popover>
    </div>
  );
}
