import { describe, it, expect } from "vitest";
import { detectBank } from "@/lib/documents/parsers/detect-bank";

describe("documents/parsers/detect-bank", () => {
  it("identifies HDFC", () => {
    expect(detectBank("HDFC BANK\nStatement of Account\nA/C 12345")).toBe(
      "HDFC"
    );
    expect(detectBank("welcome to HDFC bank account statement")).toBe("HDFC");
  });

  it("identifies ICICI", () => {
    expect(detectBank("ICICI Bank Account Statement\nDear customer")).toBe(
      "ICICI"
    );
    expect(detectBank("Generated by ICICI net banking")).toBe("ICICI");
  });

  it("identifies Axis Bank", () => {
    expect(detectBank("AXIS BANK LIMITED Statement")).toBe("AXIS");
  });

  it("identifies SBI (State Bank of India)", () => {
    expect(detectBank("State Bank of India Account Statement")).toBe("SBI");
  });

  it("identifies Kotak", () => {
    expect(detectBank("Kotak Mahindra Bank Statement")).toBe("KOTAK");
  });

  it("identifies IDFC First Bank", () => {
    expect(detectBank("IDFC FIRST Bank Statement of Account")).toBe("IDFC");
  });

  it("returns UNKNOWN when no rule matches", () => {
    expect(detectBank("Some random text not from a bank")).toBe("UNKNOWN");
    expect(detectBank("")).toBe("UNKNOWN");
    expect(detectBank(null)).toBe("UNKNOWN");
    expect(detectBank(undefined)).toBe("UNKNOWN");
  });

  it("is case-insensitive", () => {
    expect(detectBank("hdfc bank account statement")).toBe("HDFC");
    expect(detectBank("ICICI bank ledger")).toBe("ICICI");
  });
});
