"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Combobox, type ComboboxOption } from "@/components/ui/combobox";
import { DatePicker } from "@/components/shared/date-picker";
import { MoneyInput } from "@/components/shared/money-input";
import {
  TransactionLineItemsTable,
  type LineItem,
  type ItemOption,
  type TaxOption,
} from "@/components/shared/transaction-line-items-table";
import { AttachFilesField, type AttachedFile } from "@/components/shared/attach-files-field";
import { PdfTemplatePicker } from "@/components/shared/pdf-template-picker";
import { NumberSeriesPopover } from "@/components/shared/number-series-popover";
import { CustomerSearchDialog } from "@/components/shared/customer-search-dialog";
import { updateNumberSeriesInlineAction } from "@/app/(dashboard)/settings/number-series/inline-actions";
import type { QuoteInput } from "@/lib/validations/quote";
import { format } from "date-fns";
import { toast } from "sonner";

export type QuoteFormProps = {
  initial?: Partial<QuoteInput>;
  nextNumber: string;
  contactOptions: ComboboxOption[];
  itemOptions: ItemOption[];
  taxOptions: TaxOption[];
  salespersonOptions: ComboboxOption[];
  pdfTemplateOptions?: ComboboxOption[];
  /** All Project rows for the org — the form filters client-side by
   *  selected customer per <quotes_spec>: "only projects of the
   *  selected customer". */
  projectOptions?: { value: string; label: string; customerId: string | null }[];
  /** Server action that creates a new Salesperson row inline. */
  createSalesperson?: (input: { name: string }) => Promise<{ id: string; name: string }>;
  /** Server action that creates a minimal Customer inline. */
  createCustomer?: (input: { displayName: string; email?: string | null }) => Promise<{ id: string; displayName: string }>;
  /** Current number-series row for the popover (optional — when omitted,
   *  the form falls back to a plain disabled input). */
  numberSeries?: { prefix: string; nextValue: number; padding: number; isAutoGenerated: boolean };
  defaultCurrency: string;
  onSubmitAction: (
    values: QuoteInput,
    opts?: { send?: boolean }
  ) => Promise<unknown>;
  submitLabel?: string;
  cancelHref?: string;
  initialLines?: LineItem[];
};

export function QuoteForm({
  initial,
  nextNumber,
  contactOptions,
  itemOptions,
  taxOptions,
  salespersonOptions,
  pdfTemplateOptions = [],
  projectOptions = [],
  createSalesperson,
  createCustomer,
  numberSeries,
  defaultCurrency,
  onSubmitAction,
  submitLabel = "Save as Draft",
  cancelHref = "/sales/quotes",
  initialLines,
}: QuoteFormProps) {
  const router = useRouter();
  const [busy, setBusy] = React.useState<"idle" | "draft" | "send">("idle");
  const [contactId, setContactId] = React.useState<string | null>(
    initial?.contactId ?? null
  );
  const [referenceNumber, setReferenceNumber] = React.useState(
    initial?.referenceNumber ?? ""
  );
  const [quoteDate, setQuoteDate] = React.useState<Date>(
    initial?.quoteDate ? new Date(initial.quoteDate as unknown as string) : new Date()
  );
  const [expiryDate, setExpiryDate] = React.useState<Date | null>(
    initial?.expiryDate ? new Date(initial.expiryDate as unknown as string) : null
  );
  const [salespersonId, setSalespersonId] = React.useState<string | null>(
    initial?.salespersonId ?? null
  );
  const [projectId, setProjectId] = React.useState<string | null>(
    initial?.projectId ?? null
  );
  const [subject, setSubject] = React.useState(initial?.subject ?? "");
  const [discountValue, setDiscountValue] = React.useState(
    String((initial?.documentDiscount?.value as number | undefined) ?? "0")
  );
  const [discountType, setDiscountType] = React.useState<"percentage" | "amount">(
    initial?.documentDiscount?.type ?? "percentage"
  );
  const [adjustmentLabel, setAdjustmentLabel] = React.useState(
    initial?.adjustmentLabel ?? "Adjustment"
  );
  const [adjustmentValue, setAdjustmentValue] = React.useState(
    String((initial?.adjustmentValue as number | undefined) ?? "0")
  );
  const [customerNotes, setCustomerNotes] = React.useState(
    initial?.customerNotes ?? "Looking forward to your business."
  );
  const [terms, setTerms] = React.useState(initial?.termsAndConditions ?? "");
  const [pdfTemplateId, setPdfTemplateId] = React.useState<string | null>(
    initial?.pdfTemplateId ?? null
  );
  const [attachments, setAttachments] = React.useState<AttachedFile[]>(
    (initial?.attachments as AttachedFile[] | undefined) ?? []
  );
  // Mutable state for the inline-create patterns — the parent passes the
  // initial server-loaded list; we append on inline create so the new
  // option is selectable in the same submit cycle.
  const [contactsState, setContactsState] = React.useState(contactOptions);
  const [salespeopleState, setSalespeopleState] = React.useState(salespersonOptions);
  const [lines, setLines] = React.useState<LineItem[]>(initialLines ?? []);

  async function submit(send: boolean) {
    if (!contactId) {
      toast.error("Pick a customer");
      return;
    }
    if (lines.length === 0 || lines.every((l) => !l.name)) {
      toast.error("Add at least one line item");
      return;
    }
    setBusy(send ? "send" : "draft");
    const payload: QuoteInput = {
      contactId,
      referenceNumber: referenceNumber || null,
      quoteDate: format(quoteDate, "yyyy-MM-dd") as unknown as Date,
      expiryDate: expiryDate
        ? (format(expiryDate, "yyyy-MM-dd") as unknown as Date)
        : null,
      salespersonId,
      projectId,
      subject: subject || null,
      status: send ? "SENT" : "DRAFT",
      currency: defaultCurrency,
      documentDiscount: { value: Number(discountValue || 0), type: discountType },
      adjustmentLabel,
      adjustmentValue: Number(adjustmentValue || 0),
      customerNotes,
      termsAndConditions: terms || null,
      pdfTemplateId: pdfTemplateId,
      attachments,
      lines: lines
        .filter((l) => l.name.trim())
        .map((l, i) => ({
          itemId: l.itemId ?? null,
          position: i,
          name: l.name,
          description: l.description ?? null,
          hsnSacCode: l.hsnSacCode ?? null,
          quantity: Number(l.quantity || 0),
          unit: l.unit ?? null,
          rate: Number(l.rate || 0),
          discount: Number(l.discount || 0),
          discountType: l.discountType ?? "percentage",
          taxId: l.taxId ?? null,
        })),
    };
    try {
      await onSubmitAction(payload, { send });
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Save failed");
      setBusy("idle");
    }
  }

  return (
    <div className="space-y-6">
      <section className="rounded-md border bg-card p-6 grid gap-4 md:grid-cols-[10rem_1fr]">
        <Label className="pt-2">Customer Name *</Label>
        <div className="flex items-center gap-2">
          <div className="flex-1">
            <Combobox
              options={contactsState}
              value={contactId}
              onChange={(v) => setContactId(v)}
              placeholder="Select customer…"
              testId="quote-customer-combobox"
              allowCreate={!!createCustomer}
              onCreate={
                createCustomer
                  ? async (input: string) => {
                      try {
                        const created = await createCustomer({
                          displayName: input,
                          email: null,
                        });
                        setContactsState((prev) => [
                          ...prev,
                          { value: created.id, label: created.displayName },
                        ]);
                        setContactId(created.id);
                      } catch (err) {
                        toast.error(
                          err instanceof Error ? err.message : "Couldn't create customer"
                        );
                      }
                    }
                  : undefined
              }
            />
          </div>
          <CustomerSearchDialog
            onSelect={(c) => {
              if (!contactsState.find((o) => o.value === c.id)) {
                setContactsState((prev) => [
                  ...prev,
                  { value: c.id, label: c.displayName },
                ]);
              }
              setContactId(c.id);
            }}
          />
        </div>

        <Label className="pt-2">Quote #</Label>
        {!initial && numberSeries ? (
          <NumberSeriesPopover
            module="quote"
            current={nextNumber}
            prefix={numberSeries.prefix}
            nextValue={numberSeries.nextValue}
            padding={numberSeries.padding}
            isAutoGenerated={numberSeries.isAutoGenerated}
            action={updateNumberSeriesInlineAction}
          />
        ) : (
          <Input value={initial ? "(unchanged)" : nextNumber} disabled className="font-mono" />
        )}

        <Label className="pt-2">Reference #</Label>
        <Input
          value={referenceNumber ?? ""}
          onChange={(e) => setReferenceNumber(e.target.value)}
          placeholder="Optional"
        />

        <Label className="pt-2">Quote Date *</Label>
        <DatePicker value={quoteDate} onChange={(d) => d && setQuoteDate(d)} />

        <Label className="pt-2">Expiry Date</Label>
        <DatePicker value={expiryDate} onChange={(d) => setExpiryDate(d)} />

        <Label className="pt-2">Salesperson</Label>
        <Combobox
          options={salespeopleState}
          value={salespersonId}
          onChange={(v) => setSalespersonId(v)}
          placeholder="Optional"
          allowCreate={!!createSalesperson}
          onCreate={
            createSalesperson
              ? async (input: string) => {
                  try {
                    const created = await createSalesperson({ name: input });
                    setSalespeopleState((prev) => [
                      ...prev,
                      { value: created.id, label: created.name },
                    ]);
                    setSalespersonId(created.id);
                  } catch (err) {
                    toast.error(
                      err instanceof Error ? err.message : "Couldn't add salesperson"
                    );
                  }
                }
              : undefined
          }
        />

        <Label className="pt-2">Project Name</Label>
        <div className="space-y-1">
          <Combobox
            options={projectOptions
              .filter((p) => !contactId || p.customerId === contactId)
              .map((p) => ({ value: p.value, label: p.label }))}
            value={projectId}
            onChange={(v) => setProjectId(v)}
            placeholder={
              contactId
                ? "Select a project for this customer"
                : "Select a customer first"
            }
            disabled={!contactId}
          />
          {!contactId ? (
            <p className="text-xs text-muted-foreground">
              Select a customer to associate a project.
            </p>
          ) : null}
        </div>

        <Label className="pt-2">Subject</Label>
        <Textarea
          value={subject ?? ""}
          onChange={(e) => setSubject(e.target.value)}
          rows={2}
          placeholder="Let your customer know what this Quote is for"
        />
      </section>

      <TransactionLineItemsTable
        itemOptions={itemOptions}
        taxOptions={taxOptions}
        documentDiscount={{ value: discountValue, type: discountType }}
        adjustment={adjustmentValue}
        onChange={(ls) => setLines(ls)}
        initialLines={initialLines}
      />

      <section className="grid gap-4 md:grid-cols-2">
        <div className="space-y-3">
          <Label htmlFor="customer-notes">Customer Notes</Label>
          <Textarea
            id="customer-notes"
            value={customerNotes ?? ""}
            onChange={(e) => setCustomerNotes(e.target.value)}
            rows={3}
          />
          <Label htmlFor="terms">Terms &amp; Conditions</Label>
          <Textarea
            id="terms"
            value={terms ?? ""}
            onChange={(e) => setTerms(e.target.value)}
            rows={3}
          />
        </div>
        <div className="rounded-md border p-4 space-y-3 text-sm">
          <div className="flex items-center justify-between gap-2">
            <Label htmlFor="discount">Document discount</Label>
            <div className="flex items-center gap-1">
              <MoneyInput
                value={discountValue}
                onChange={(v) => setDiscountValue(v)}
              />
              <select
                value={discountType}
                onChange={(e) => setDiscountType(e.target.value as "percentage" | "amount")}
                className="h-10 rounded border px-2 bg-background"
                aria-label="Discount type"
              >
                <option value="percentage">%</option>
                <option value="amount">{defaultCurrency}</option>
              </select>
            </div>
          </div>
          <div className="flex items-center justify-between gap-2">
            <Input
              value={adjustmentLabel ?? ""}
              onChange={(e) => setAdjustmentLabel(e.target.value)}
              className="max-w-[10rem]"
            />
            <MoneyInput
              value={adjustmentValue}
              onChange={(v) => setAdjustmentValue(v)}
              allowNegative
            />
          </div>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-2">
        <div>
          <AttachFilesField
            initial={attachments}
            onChange={setAttachments}
            maxFiles={5}
            maxSizeMb={10}
            label="Attach files to Quote"
          />
        </div>
        {pdfTemplateOptions.length > 0 ? (
          <PdfTemplatePicker
            templates={pdfTemplateOptions}
            value={pdfTemplateId}
            onChange={setPdfTemplateId}
          />
        ) : null}
      </section>

      <div className="flex items-center gap-2 sticky bottom-0 bg-background border-t -mx-6 px-6 py-3">
        <Button
          type="button"
          onClick={() => submit(false)}
          disabled={busy !== "idle"}
          className="gap-1"
        >
          {busy === "draft" ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
          {submitLabel}
        </Button>
        <Button
          type="button"
          variant="outline"
          onClick={() => submit(true)}
          disabled={busy !== "idle"}
          className="gap-1"
        >
          {busy === "send" ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
          Save and Send
        </Button>
        <Button
          type="button"
          variant="ghost"
          onClick={() => router.push(cancelHref)}
        >
          Cancel
        </Button>
      </div>
    </div>
  );
}
