"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import {
  ArrowLeft,
  ArrowRight,
  BookOpen,
  Calendar,
  ChevronDown,
  ChevronRight,
  GripVertical,
  Plus,
  PlusCircle,
  Search,
  Settings,
  X,
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Combobox } from "@/components/ui/combobox";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { cn } from "@/lib/utils";
import { createCustomReportAction } from "@/app/(dashboard)/reports/actions";
import {
  addReportColumn,
  addSection,
  availableReportColumns,
  DEFAULT_REPORT_COLUMNS,
  removeReportColumn,
  removeReportNode,
  renameReportNode,
  reportColumn,
  reportColumnLabel,
  toEditableReportNodes,
  type CustomReportSectionNode,
  type EditableReportNode,
} from "@/lib/reports/custom-report-structure";

/**
 * REPORTS — "Create Custom Report" 4-step wizard (Phase 1).
 *
 * Mirrors Zoho's Create Custom Report flow:
 *   Step 1 General — fully functional: Date Range, Report Basis,
 *     Filter Accounts, a Compare section, and Advanced Filters (add /
 *     remove filter rows; not yet wired into any query).
 *   Steps 2-4 (Customize Rows and Columns / Report Layout / Report
 *     Preferences) — navigable scaffolds for now. Preferences also
 *     exposes the report-name field used on Create.
 *
 * On the final step, Create persists the report via
 * `createCustomReportAction` ({ name, reportKey, params }) and routes
 * to /reports?tab=my. `params` is built from the General selections as
 * a URL query string (the same shape report pages read).
 */

type WizardProps = {
  baseKey: string;
  baseName: string;
  baseHref: string | null;
  /**
   * Step 2 structural node list (sections + formula rows in display
   * order). `null` for report types without a structure editor yet —
   * Step 2 then shows a "coming soon" message. Built server-side by
   * `buildCustomReportStructure` from the org's Chart of Accounts.
   */
  structure: CustomReportSectionNode[] | null;
  /**
   * Current organization name — shown in the Step 3 Preview pane when
   * "Organization Name" is toggled on.
   */
  orgName: string;
  /**
   * Org details rendered as one line each (e.g. address, country, email).
   * Shown in the Step 3 Preview pane when "Organization Details" is toggled
   * on. Page builds this from the organization record.
   */
  orgDetailsLines: string[];
  /**
   * Current user's first name (or email local-part as a fallback) — shown
   * in the Step 3 Preview footer when "Generated By" is toggled on.
   */
  userFirstName: string | null;
};

type AdvancedFilter = {
  id: string;
  field: string;
  op: string;
  value: string;
};

const STEPS = [
  "General",
  "Customize Rows and Columns",
  "Report Layout",
  "Report Preferences",
] as const;

const DATE_RANGE_OPTIONS: { value: string; label: string }[] = [
  { value: "today", label: "Today" },
  { value: "this-month", label: "This Month" },
  { value: "this-quarter", label: "This Quarter" },
  { value: "this-year", label: "This Year" },
  { value: "previous-month", label: "Previous Month" },
  { value: "previous-quarter", label: "Previous Quarter" },
  { value: "previous-year", label: "Previous Year" },
  { value: "custom", label: "Custom" },
];

// "Compare With" (under "Compare Based on Period/Year"). None = no
// comparison column; the other two add a prior-year / prior-period
// column to the report.
const COMPARE_OPTIONS: { value: string; label: string }[] = [
  { value: "none", label: "None" },
  { value: "previous-year", label: "Previous Year(s)" },
  { value: "previous-period", label: "Previous Period(s)" },
];

// "Filter Accounts" modes (Zoho-parity). These are filter *modes*, not
// individual accounts — `hint` renders as the sub-description in the
// Combobox dropdown.
const FILTER_ACCOUNT_OPTIONS: { value: string; label: string; hint: string }[] =
  [
    {
      value: "without-zero-balance",
      label: "Accounts Without Zero Balance",
      hint: "Filter every account except the ones with zero-balance.",
    },
    {
      value: "all",
      label: "All Accounts",
      hint: "Filter all accounts, including the ones with zero-balance.",
    },
    {
      value: "with-transactions",
      label: "Accounts With Transactions",
      hint: "Filter the accounts with transactions that were created during the specified period.",
    },
  ];

const FILTER_OP_OPTIONS: { value: string; label: string }[] = [
  { value: "equals", label: "equals" },
  { value: "not-equals", label: "not equals" },
  { value: "contains", label: "contains" },
  { value: "greater-than", label: "greater than" },
  { value: "less-than", label: "less than" },
];

const STEP_PLACEHOLDER: Record<number, string> = {
  3: "Report Preferences — configured in an upcoming step.",
};

/** Shared styling for native <select> controls to match the Input. */
const SELECT_CLASS =
  "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50";

function newFilterId(): string {
  return typeof crypto !== "undefined" && crypto.randomUUID
    ? crypto.randomUUID()
    : String(Date.now());
}

export function CustomReportWizard({
  baseKey,
  baseName,
  structure,
  orgName,
  orgDetailsLines,
  userFirstName,
}: WizardProps) {
  const router = useRouter();

  const [step, setStep] = React.useState(0);

  // ── Step 1 (General) state ──────────────────────────────────────
  const [dateRange, setDateRange] = React.useState("today");
  const [reportBasis, setReportBasis] = React.useState("accrual");
  const [filterAccount, setFilterAccount] = React.useState<string | null>(
    "all"
  );
  const [compareWith, setCompareWith] = React.useState("none");
  // "Compare Based on Period/Year" is a collapsible section (Zoho-style);
  // open by default so the Compare With control shows.
  const [compareOpen, setCompareOpen] = React.useState(true);
  const [advancedFilters, setAdvancedFilters] = React.useState<
    AdvancedFilter[]
  >([]);

  // Report name — defaults to the base report name, edited in
  // Preferences (step 3) and required on Create.
  const [name, setName] = React.useState(baseName);

  // ── Step 3 (Report Layout) state ────────────────────────────────
  // "Choose Details to Display" checkboxes
  const [showOrgName, setShowOrgName] = React.useState(true);
  const [showOrgDetails, setShowOrgDetails] = React.useState(false);
  const [showReportBasis, setShowReportBasis] = React.useState(true);
  const [showPageNumber, setShowPageNumber] = React.useState(false);
  const [showGeneratedBy, setShowGeneratedBy] = React.useState(false);
  const [showGeneratedDate, setShowGeneratedDate] = React.useState(false);
  const [showGeneratedTime, setShowGeneratedTime] = React.useState(false);
  // "Report Layout" controls
  const [tableDensity, setTableDensity] = React.useState<
    "classic" | "compact" | "comfortable"
  >("classic");
  const [autoResize, setAutoResize] = React.useState(true);
  const [paperSize, setPaperSize] = React.useState<"a4" | "letter">("a4");
  const [orientation, setOrientation] = React.useState<
    "portrait" | "landscape"
  >("portrait");
  const [fontFamily, setFontFamily] = React.useState<"ubuntu" | "default">(
    "ubuntu"
  );
  const [marginTop, setMarginTop] = React.useState(0.7);
  const [marginBottom, setMarginBottom] = React.useState(0.7);
  const [marginLeft, setMarginLeft] = React.useState(0.55);
  const [marginRight, setMarginRight] = React.useState(0.2);

  const [pending, startTransition] = React.useTransition();

  function addFilter() {
    setAdvancedFilters((rows) => [
      ...rows,
      { id: newFilterId(), field: "", op: "equals", value: "" },
    ]);
  }

  function updateFilter(id: string, patch: Partial<AdvancedFilter>) {
    setAdvancedFilters((rows) =>
      rows.map((r) => (r.id === id ? { ...r, ...patch } : r))
    );
  }

  function removeFilter(id: string) {
    setAdvancedFilters((rows) => rows.filter((r) => r.id !== id));
  }

  function onCreate() {
    const params = new URLSearchParams();
    if (dateRange) params.set("dateRange", dateRange);
    if (reportBasis) params.set("basis", reportBasis);
    if (filterAccount && filterAccount !== "all")
      params.set("account", filterAccount);
    if (compareWith && compareWith !== "none")
      params.set("compareWith", compareWith);
    // Step 3 Report Layout — only emit when non-default (keeps URLs short).
    if (!showOrgName) params.set("showOrgName", "false");
    if (showOrgDetails) params.set("showOrgDetails", "true");
    if (!showReportBasis) params.set("showReportBasis", "false");
    if (showPageNumber) params.set("showPageNumber", "true");
    if (showGeneratedBy) params.set("showGeneratedBy", "true");
    if (showGeneratedDate) params.set("showGeneratedDate", "true");
    if (showGeneratedTime) params.set("showGeneratedTime", "true");
    if (tableDensity !== "classic") params.set("tableDensity", tableDensity);
    if (!autoResize) params.set("autoResize", "false");
    if (paperSize !== "a4") params.set("paperSize", paperSize);
    if (orientation !== "portrait") params.set("orientation", orientation);
    if (fontFamily !== "ubuntu") params.set("fontFamily", fontFamily);
    if (marginTop !== 0.7) params.set("marginTop", String(marginTop));
    if (marginBottom !== 0.7) params.set("marginBottom", String(marginBottom));
    if (marginLeft !== 0.55) params.set("marginLeft", String(marginLeft));
    if (marginRight !== 0.2) params.set("marginRight", String(marginRight));

    startTransition(async () => {
      const res = await createCustomReportAction({
        name: name.trim(),
        reportKey: baseKey,
        params: params.toString(),
      });
      if (res.ok) {
        toast.success("Custom report created");
        router.push("/reports?tab=my");
      } else {
        toast.error(res.error ?? "Couldn't create custom report");
      }
    });
  }

  const canCreate = Boolean(name.trim()) && !pending;

  return (
    <div className="flex flex-col min-h-[calc(100vh-4rem)]">
      {/* ───── Top bar: title + X close ───── */}
      <div className="flex items-center justify-between border-b bg-card px-6 py-4 sticky top-0 z-10">
        <h1 className="text-xl font-semibold leading-tight">
          Create Custom Report
        </h1>
        <Button
          type="button"
          variant="ghost"
          size="icon"
          aria-label="Close"
          className="rounded-full"
          onClick={() => router.push("/reports")}
        >
          <X className="h-4 w-4" />
        </Button>
      </div>

      {/* ───── Step indicator ───── */}
      <div className="border-b bg-muted/30 px-6 py-3">
        <ol className="flex flex-wrap items-center gap-x-2 gap-y-2 text-sm">
          {STEPS.map((label, i) => {
            const active = i === step;
            const completed = i < step;
            return (
              <li key={label} className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => setStep(i)}
                  className={cn(
                    "flex items-center gap-2 rounded-md px-1.5 py-1 transition-colors",
                    active
                      ? "text-primary font-semibold"
                      : completed
                        ? "text-foreground/70 hover:text-foreground"
                        : "text-muted-foreground hover:text-foreground"
                  )}
                >
                  <span
                    className={cn(
                      "flex h-6 w-6 shrink-0 items-center justify-center rounded-full border text-xs font-medium",
                      active
                        ? "border-primary bg-primary text-primary-foreground"
                        : completed
                          ? "border-primary/40 bg-primary/10 text-primary"
                          : "border-input bg-background text-muted-foreground"
                    )}
                  >
                    {i + 1}
                  </span>
                  <span>{label}</span>
                </button>
                {i < STEPS.length - 1 ? (
                  <ChevronRight className="h-4 w-4 text-muted-foreground" />
                ) : null}
              </li>
            );
          })}
        </ol>
      </div>

      {/* ───── Body ───── */}
      <div className="flex-1 px-6 py-6">
        {step === 0 ? (
          <div className="max-w-4xl space-y-6">
            {/* General fields — stacked labels, 2-column grid */}
            <div className="grid grid-cols-1 gap-x-8 gap-y-5 sm:grid-cols-2">
              {/* Date Range (own row) */}
              <div className="space-y-1.5">
                <Label htmlFor="cr-date-range">Date Range</Label>
                <div className="relative">
                  <Calendar className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <select
                    id="cr-date-range"
                    value={dateRange}
                    onChange={(e) => setDateRange(e.target.value)}
                    className={cn(SELECT_CLASS, "pl-9")}
                  >
                    {DATE_RANGE_OPTIONS.map((o) => (
                      <option key={o.value} value={o.value}>
                        {o.label}
                      </option>
                    ))}
                  </select>
                </div>
              </div>
              {/* keep Date Range alone on its row */}
              <div className="hidden sm:block" aria-hidden />

              {/* Report Basis */}
              <div className="space-y-1.5">
                <Label htmlFor="cr-report-basis">Report Basis</Label>
                <select
                  id="cr-report-basis"
                  value={reportBasis}
                  onChange={(e) => setReportBasis(e.target.value)}
                  className={SELECT_CLASS}
                >
                  <option value="accrual">Accrual</option>
                  <option value="cash">Cash</option>
                </select>
              </div>

              {/* Filter Accounts */}
              <div className="space-y-1.5">
                <Label>Filter Accounts</Label>
                <Combobox
                  options={FILTER_ACCOUNT_OPTIONS}
                  value={filterAccount}
                  onChange={setFilterAccount}
                  placeholder="All Accounts"
                  stackedOptions
                />
              </div>
            </div>

            <div className="border-t border-border" />

            {/* COMPARE section */}
            <div className="space-y-4">
              <div className="space-y-2">
                <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Compare
                </h2>
                <button
                  type="button"
                  onClick={() => setCompareOpen((o) => !o)}
                  aria-expanded={compareOpen}
                  className="flex items-center gap-1.5 text-sm font-semibold"
                >
                  Compare Based on Period/Year
                  <ChevronDown
                    className={cn(
                      "h-4 w-4 text-muted-foreground transition-transform",
                      compareOpen ? "" : "-rotate-90"
                    )}
                  />
                </button>
              </div>
              {compareOpen ? (
                <div className="grid grid-cols-1 gap-x-8 sm:grid-cols-2">
                  <div className="space-y-1.5">
                    <Label htmlFor="cr-compare-with">Compare With</Label>
                    <select
                      id="cr-compare-with"
                      value={compareWith}
                      onChange={(e) => setCompareWith(e.target.value)}
                      className={SELECT_CLASS}
                    >
                      {COMPARE_OPTIONS.map((o) => (
                        <option key={o.value} value={o.value}>
                          {o.label}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>
              ) : null}
            </div>

            <div className="border-t border-border" />

            {/* Advanced Filters section */}
            <div className="space-y-3">
              <div className="space-y-1">
                <h2 className="text-base font-semibold">Advanced Filters</h2>
                <p className="text-sm text-muted-foreground">
                  Use advanced filters to filter the report based on its fields.
                </p>
              </div>

              {advancedFilters.length > 0 ? (
                <div className="space-y-3">
                  {advancedFilters.map((f) => (
                    <div
                      key={f.id}
                      className="flex flex-wrap items-center gap-2"
                    >
                      <Input
                        value={f.field}
                        onChange={(e) =>
                          updateFilter(f.id, { field: e.target.value })
                        }
                        placeholder="Field name"
                        className="w-48"
                        aria-label="Filter field"
                      />
                      <select
                        value={f.op}
                        onChange={(e) =>
                          updateFilter(f.id, { op: e.target.value })
                        }
                        className={cn(SELECT_CLASS, "w-40")}
                        aria-label="Filter operator"
                      >
                        {FILTER_OP_OPTIONS.map((o) => (
                          <option key={o.value} value={o.value}>
                            {o.label}
                          </option>
                        ))}
                      </select>
                      <Input
                        value={f.value}
                        onChange={(e) =>
                          updateFilter(f.id, { value: e.target.value })
                        }
                        placeholder="Value"
                        className="w-48"
                        aria-label="Filter value"
                      />
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon"
                        aria-label="Remove filter"
                        onClick={() => removeFilter(f.id)}
                      >
                        <X className="h-4 w-4" />
                      </Button>
                    </div>
                  ))}
                </div>
              ) : null}

              <button
                type="button"
                onClick={addFilter}
                className="inline-flex items-center gap-1.5 text-sm font-medium text-primary hover:underline"
              >
                <PlusCircle className="h-4 w-4" />
                Add Filters
              </button>
            </div>
          </div>
        ) : step === 1 ? (
          <div className="w-full">
            <CustomizeRowsAndColumns
              rootLabel={baseName}
              structure={structure}
            />
          </div>
        ) : step === 2 ? (
          <div className="max-w-6xl">
            <div className="grid grid-cols-1 gap-8 lg:grid-cols-[1fr_22rem]">
              <div className="space-y-6">
            {/* ── Choose Details to Display ─────────────────────── */}
            <div className="space-y-3">
              <h2 className="text-base font-semibold">
                Choose Details to Display
              </h2>
              <div className="grid grid-cols-1 gap-x-6 gap-y-2 text-sm sm:grid-cols-3">
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={showOrgName}
                    onChange={(e) => setShowOrgName(e.target.checked)}
                    className="accent-primary"
                  />
                  Organization Name
                </label>
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={showOrgDetails}
                    onChange={(e) => setShowOrgDetails(e.target.checked)}
                    className="accent-primary"
                  />
                  Organization Details
                  <Settings
                    className="h-3.5 w-3.5 text-muted-foreground"
                    aria-hidden
                  />
                </label>
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={showReportBasis}
                    onChange={(e) => setShowReportBasis(e.target.checked)}
                    className="accent-primary"
                  />
                  Report Basis
                </label>
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={showPageNumber}
                    onChange={(e) => setShowPageNumber(e.target.checked)}
                    className="accent-primary"
                  />
                  Page Number
                </label>
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={showGeneratedBy}
                    onChange={(e) => setShowGeneratedBy(e.target.checked)}
                    className="accent-primary"
                  />
                  Generated By
                </label>
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={showGeneratedDate}
                    onChange={(e) => setShowGeneratedDate(e.target.checked)}
                    className="accent-primary"
                  />
                  Generated Date
                </label>
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={showGeneratedTime}
                    onChange={(e) => setShowGeneratedTime(e.target.checked)}
                    className="accent-primary"
                  />
                  Generated Time
                </label>
              </div>
            </div>

            <div className="border-t border-border" />

            {/* ── Report Layout ─────────────────────────────────── */}
            <div className="space-y-4">
              <h2 className="text-base font-semibold">Report Layout</h2>

              {/* Table Density */}
              <div className="space-y-1.5">
                <Label htmlFor="cr-table-density">Table Density</Label>
                <select
                  id="cr-table-density"
                  value={tableDensity}
                  onChange={(e) =>
                    setTableDensity(
                      e.target.value as "classic" | "compact" | "comfortable"
                    )
                  }
                  className={cn(SELECT_CLASS, "max-w-sm")}
                >
                  <option value="classic">Classic</option>
                  <option value="compact">Compact</option>
                  <option value="comfortable">Comfortable</option>
                </select>
              </div>

              {/* Auto-resize */}
              <label className="flex items-start gap-2 text-sm">
                <input
                  type="checkbox"
                  checked={autoResize}
                  onChange={(e) => setAutoResize(e.target.checked)}
                  className="mt-0.5 accent-primary"
                />
                <span>
                  Re-size the table and its font automatically to fit the
                  content within the table.
                </span>
              </label>

              {/* Paper Size + Orientation */}
              <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
                <div className="space-y-1.5">
                  <Label>Paper Size</Label>
                  <div className="flex items-center gap-4 text-sm">
                    <label className="flex items-center gap-1.5">
                      <input
                        type="radio"
                        name="cr-paper-size"
                        value="a4"
                        checked={paperSize === "a4"}
                        onChange={() => setPaperSize("a4")}
                        className="accent-primary"
                      />
                      A4
                    </label>
                    <label className="flex items-center gap-1.5">
                      <input
                        type="radio"
                        name="cr-paper-size"
                        value="letter"
                        checked={paperSize === "letter"}
                        onChange={() => setPaperSize("letter")}
                        className="accent-primary"
                      />
                      Letter
                    </label>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <Label>Orientation</Label>
                  <div className="flex items-center gap-4 text-sm">
                    <label className="flex items-center gap-1.5">
                      <input
                        type="radio"
                        name="cr-orientation"
                        value="portrait"
                        checked={orientation === "portrait"}
                        onChange={() => setOrientation("portrait")}
                        className="accent-primary"
                      />
                      Portrait
                    </label>
                    <label className="flex items-center gap-1.5">
                      <input
                        type="radio"
                        name="cr-orientation"
                        value="landscape"
                        checked={orientation === "landscape"}
                        onChange={() => setOrientation("landscape")}
                        className="accent-primary"
                      />
                      Landscape
                    </label>
                  </div>
                </div>
              </div>

              {/* Font Family + Margins */}
              <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
                <div className="space-y-1.5">
                  <Label htmlFor="cr-font-family">Font Family</Label>
                  <select
                    id="cr-font-family"
                    value={fontFamily}
                    onChange={(e) =>
                      setFontFamily(e.target.value as "ubuntu" | "default")
                    }
                    className={SELECT_CLASS}
                  >
                    <option value="ubuntu">Ubuntu</option>
                    <option value="default">Default</option>
                  </select>
                  <p className="text-xs text-muted-foreground">
                    Supports English and European languages. This font can
                    also render Indian Rupees Symbol.
                  </p>
                </div>
                <div className="space-y-1.5">
                  <Label>Margins</Label>
                  <div className="grid grid-cols-4 gap-2">
                    <div className="space-y-1">
                      <Input
                        type="number"
                        step="0.05"
                        value={marginTop}
                        onChange={(e) =>
                          setMarginTop(parseFloat(e.target.value) || 0)
                        }
                        aria-label="Top margin"
                      />
                      <p className="text-center text-xs text-muted-foreground">
                        Top
                      </p>
                    </div>
                    <div className="space-y-1">
                      <Input
                        type="number"
                        step="0.05"
                        value={marginBottom}
                        onChange={(e) =>
                          setMarginBottom(parseFloat(e.target.value) || 0)
                        }
                        aria-label="Bottom margin"
                      />
                      <p className="text-center text-xs text-muted-foreground">
                        Bottom
                      </p>
                    </div>
                    <div className="space-y-1">
                      <Input
                        type="number"
                        step="0.05"
                        value={marginLeft}
                        onChange={(e) =>
                          setMarginLeft(parseFloat(e.target.value) || 0)
                        }
                        aria-label="Left margin"
                      />
                      <p className="text-center text-xs text-muted-foreground">
                        Left
                      </p>
                    </div>
                    <div className="space-y-1">
                      <Input
                        type="number"
                        step="0.05"
                        value={marginRight}
                        onChange={(e) =>
                          setMarginRight(parseFloat(e.target.value) || 0)
                        }
                        aria-label="Right margin"
                      />
                      <p className="text-center text-xs text-muted-foreground">
                        Right
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
              </div>
              {/* ── Preview pane ─────────────────────────────────── */}
              <aside>
                <div className="mb-2 text-center text-xs uppercase tracking-wider text-muted-foreground">
                  Preview
                </div>
                <div className="space-y-3 rounded-md border bg-card p-6 shadow-sm">
                  {/* Header: org name + (org details lines) + basis */}
                  <div className="space-y-1 text-center">
                    {showOrgName ? (
                      <div className="text-sm text-muted-foreground">
                        {orgName}
                      </div>
                    ) : null}
                    {showOrgDetails
                      ? orgDetailsLines.map((line, i) => (
                          <div
                            key={i}
                            className="text-xs text-muted-foreground"
                          >
                            {line}
                          </div>
                        ))
                      : null}
                    {showReportBasis ? (
                      <div className="pt-1 text-base font-semibold">
                        Basis: {reportBasis === "cash" ? "Cash" : "Accrual"}
                      </div>
                    ) : null}
                  </div>

                  {/* Body — placeholder rows */}
                  <div className="space-y-3 pt-2">
                    <div className="h-px bg-border" />
                    <div className="h-px bg-border" />
                    <div className="h-px bg-border" />
                    <div className="h-px bg-border" />
                    <div className="h-px bg-border" />
                    <div className="h-px bg-border" />
                  </div>

                  {/* Footer — 3-col: Generated By / Page Number / Date+Time */}
                  {showGeneratedBy ||
                  showPageNumber ||
                  showGeneratedDate ||
                  showGeneratedTime ? (
                    <div className="grid grid-cols-3 items-end gap-2 border-t border-border pt-2 text-xs text-muted-foreground">
                      <div className="text-left">
                        {showGeneratedBy ? userFirstName ?? "—" : null}
                      </div>
                      <div className="text-center">
                        {showPageNumber ? "Page 1 of 1" : null}
                      </div>
                      <div className="text-right">
                        {showGeneratedDate || showGeneratedTime
                          ? [
                              showGeneratedDate
                                ? new Date().toLocaleDateString("en-GB")
                                : null,
                              showGeneratedTime
                                ? new Date().toLocaleTimeString("en-US", {
                                    hour: "numeric",
                                    minute: "2-digit",
                                    hour12: true,
                                  })
                                : null,
                            ]
                              .filter(Boolean)
                              .join(" ")
                          : null}
                      </div>
                    </div>
                  ) : null}
                </div>
              </aside>
            </div>
          </div>
        ) : (
          <div className="max-w-2xl space-y-6">
            <div className="rounded-md border bg-muted/30 p-8 text-center">
              <p className="text-sm text-muted-foreground">
                {STEP_PLACEHOLDER[step]}
              </p>
            </div>
            <div className="grid grid-cols-[10rem_20rem] items-center gap-4">
              <Label htmlFor="cr-report-name">Report name</Label>
              <Input
                id="cr-report-name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Report name"
              />
            </div>
          </div>
        )}
      </div>

      {/* ───── Footer ───── */}
      <div className="sticky bottom-0 z-10 flex items-center gap-2 border-t bg-card px-6 py-3">
        {step > 0 ? (
          <Button
            type="button"
            variant="outline"
            onClick={() => setStep((s) => Math.max(0, s - 1))}
          >
            Back
          </Button>
        ) : null}
        {step < STEPS.length - 1 ? (
          <Button
            type="button"
            onClick={() => setStep((s) => Math.min(STEPS.length - 1, s + 1))}
          >
            Next
          </Button>
        ) : (
          <Button type="button" onClick={onCreate} disabled={!canCreate}>
            {pending ? "Creating…" : "Create"}
          </Button>
        )}
        <Button
          type="button"
          variant="ghost"
          onClick={() => router.push("/reports")}
        >
          Cancel
        </Button>
      </div>
    </div>
  );
}

/**
 * Step 2 body — the "Customize Table" structural tree. Renders the
 * report's account-definition hierarchy as a 3-column table
 * (Account Definition / Account / Total). The Account + Total columns
 * are intentionally empty here: this step defines *structure*, not live
 * amounts. Drag handles, "+ New Section", and "Customize Columns" render
 * for visual parity but are stubs in this phase (toast "coming soon").
 *
 * `structure === null` → report type has no structure editor yet, so we
 * show a "coming soon" message (Next still advances the wizard).
 */
function CustomizeRowsAndColumns({
  rootLabel,
  structure,
}: {
  rootLabel: string;
  structure: CustomReportSectionNode[] | null;
}) {
  if (!structure) {
    return (
      <div className="max-w-2xl">
        <div className="rounded-md border bg-muted/30 p-8 text-center">
          <p className="text-sm text-muted-foreground">
            Row and column customization for this report type is coming soon.
          </p>
        </div>
      </div>
    );
  }

  return <CustomizeTable rootLabel={rootLabel} structure={structure} />;
}

/**
 * The editable "Customize Table". Seeds a local node list from the
 * server-built structure so the row controls work live: "+ New Section"
 * appends a renamable section, each section / formula row has a remove
 * button, and custom sections are renamed inline. Drag-reorder, the
 * Customize Columns editor, persistence, and applying the structure to
 * the generated report are follow-ups.
 */
function CustomizeTable({
  rootLabel,
  structure,
}: {
  rootLabel: string;
  structure: CustomReportSectionNode[];
}) {
  const [nodes, setNodes] = React.useState<EditableReportNode[]>(() =>
    toEditableReportNodes(structure)
  );

  const [columns, setColumns] = React.useState<string[]>(
    DEFAULT_REPORT_COLUMNS
  );
  const [columnsOpen, setColumnsOpen] = React.useState(false);

  const removeButton = (id: string, label: string) => (
    <button
      type="button"
      aria-label={`Remove ${label}`}
      onClick={() => setNodes((n) => removeReportNode(n, id))}
      className="shrink-0 rounded p-1 text-muted-foreground/60 hover:bg-muted hover:text-foreground"
    >
      <X className="h-3.5 w-3.5" />
    </button>
  );

  // One empty value cell per selected column. This step defines the
  // table *structure*, so the value cells are intentionally blank.
  const valueCells = (cls: string) =>
    columns.map((key) => <td key={key} className={cls} />);

  return (
    <div className="space-y-4">
      {/* Header chrome: title + Preview pill + Customize Columns link */}
      <div className="flex items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <h2 className="text-sm font-semibold">Customize Table</h2>
          <span className="inline-flex items-center rounded-full border border-primary/30 bg-primary/10 px-2.5 py-0.5 text-xs font-medium text-primary">
            Preview
          </span>
        </div>
        <button
          type="button"
          onClick={() => setColumnsOpen(true)}
          className="text-sm font-medium text-primary hover:underline"
        >
          Customize Columns
        </button>
      </div>

      {/* Structural table: Account Definition tree + selected value columns */}
      <div className="overflow-hidden rounded-md border">
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="border-b bg-muted/40 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              <th className="px-4 py-2.5 text-left">Account Definition</th>
              {columns.map((key) => {
                const col = reportColumn(key);
                return (
                  <th
                    key={key}
                    className={cn(
                      "w-40 px-4 py-2.5",
                      col?.align === "right" ? "text-right" : "text-left"
                    )}
                  >
                    {col?.label ?? key}
                  </th>
                );
              })}
            </tr>
          </thead>
          <tbody>
            {/* Root */}
            <tr className="border-b">
              <td className="px-4 py-2.5">
                <span className="flex items-center gap-2 font-semibold">
                  <Settings className="h-4 w-4 shrink-0 text-muted-foreground" />
                  {rootLabel}
                </span>
              </td>
              {valueCells("px-4 py-2.5")}
            </tr>

            {nodes.map((node) =>
              node.kind === "section" ? (
                <React.Fragment key={node.id}>
                  {/* Section header */}
                  <tr className="border-b bg-muted/20">
                    <td className="px-4 py-2.5">
                      <div className="flex items-center justify-between gap-2 pl-4">
                        <span className="flex min-w-0 items-center gap-2 font-medium">
                          <GripVertical className="h-4 w-4 shrink-0 text-muted-foreground/40" />
                          <BookOpen className="h-4 w-4 shrink-0 text-muted-foreground" />
                          {node.custom ? (
                            <input
                              value={node.label}
                              onChange={(e) =>
                                setNodes((n) =>
                                  renameReportNode(n, node.id, e.target.value)
                                )
                              }
                              aria-label="Section name"
                              placeholder="Section name"
                              className="h-7 w-48 rounded-md border border-input bg-background px-2 text-sm font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                            />
                          ) : (
                            <span className="truncate">{node.label}</span>
                          )}
                        </span>
                        {removeButton(node.id, node.label)}
                      </div>
                    </td>
                    {valueCells("px-4 py-2.5")}
                  </tr>

                  {/* Accounts */}
                  {node.accounts.length > 0 ? (
                    node.accounts.map((acc) => (
                      <tr key={acc.id} className="border-b">
                        <td className="px-4 py-2">
                          <span className="block pl-14 text-muted-foreground">
                            {acc.name}
                          </span>
                        </td>
                        {valueCells("px-4 py-2")}
                      </tr>
                    ))
                  ) : (
                    <tr className="border-b">
                      <td className="px-4 py-2">
                        <span className="block pl-14 text-xs italic text-muted-foreground/70">
                          No accounts in this section
                        </span>
                      </td>
                      {valueCells("px-4 py-2")}
                    </tr>
                  )}

                  {/* Section total */}
                  <tr className="border-b">
                    <td className="px-4 py-2.5">
                      <span className="block pl-14 font-semibold">
                        Total for {node.label}
                      </span>
                    </td>
                    {valueCells("px-4 py-2.5")}
                  </tr>
                </React.Fragment>
              ) : (
                <tr key={node.id} className="border-b bg-muted/10">
                  <td className="px-4 py-2.5">
                    <div className="flex items-center justify-between gap-2 pl-4">
                      <span className="flex items-center gap-2 font-semibold">
                        <span className="inline-flex h-5 items-center rounded bg-primary/10 px-1.5 font-mono text-xs italic text-primary">
                          fx
                        </span>
                        {node.label}
                      </span>
                      {removeButton(node.id, node.label)}
                    </div>
                  </td>
                  {valueCells("px-4 py-2.5")}
                </tr>
              )
            )}

            {/* + New Section */}
            <tr>
              <td colSpan={1 + columns.length} className="px-4 py-2.5">
                <button
                  type="button"
                  onClick={() => setNodes(addSection)}
                  className="inline-flex items-center gap-1.5 text-sm font-medium text-primary hover:underline"
                >
                  <Plus className="h-4 w-4" />
                  New Section
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <CustomizeColumnsDialog
        open={columnsOpen}
        onOpenChange={setColumnsOpen}
        selected={columns}
        onExecute={setColumns}
      />
    </div>
  );
}

/**
 * "Customize Columns" dual-list picker (Zoho-style). Left = Available
 * Columns (catalog minus selected, searchable); right = Selected
 * Columns. Click a column to highlight it, then the middle arrow moves
 * it across (→ to select, ← to remove); double-click moves it directly.
 * Execute applies the working selection to the table; Cancel discards.
 */
function CustomizeColumnsDialog({
  open,
  onOpenChange,
  selected,
  onExecute,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  selected: string[];
  onExecute: (next: string[]) => void;
}) {
  const [working, setWorking] = React.useState<string[]>(selected);
  const [search, setSearch] = React.useState("");
  const [active, setActive] = React.useState<{
    list: "available" | "selected";
    key: string;
  } | null>(null);

  // Reset the working copy each time the dialog opens.
  React.useEffect(() => {
    if (open) {
      setWorking(selected);
      setSearch("");
      setActive(null);
    }
  }, [open, selected]);

  const available = availableReportColumns(working).filter((c) =>
    c.label.toLowerCase().includes(search.trim().toLowerCase())
  );

  function moveActive() {
    if (!active) return;
    setWorking((w) =>
      active.list === "available"
        ? addReportColumn(w, active.key)
        : removeReportColumn(w, active.key)
    );
    setActive(null);
  }

  const MoveIcon = active?.list === "selected" ? ArrowLeft : ArrowRight;

  const itemClass = (isActive: boolean) =>
    cn(
      "flex w-full items-center rounded px-2 py-1.5 text-left text-sm hover:bg-accent",
      isActive && "bg-accent"
    );

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl">
        <DialogHeader>
          <DialogTitle>Customize Columns</DialogTitle>
        </DialogHeader>

        <div className="grid grid-cols-[1fr_auto_1fr] gap-4">
          {/* Available */}
          <div className="space-y-2">
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Available Columns
            </p>
            <div className="flex h-80 flex-col rounded-md border">
              <div className="flex items-center gap-2 border-b px-3">
                <Search className="h-4 w-4 shrink-0 text-muted-foreground" />
                <input
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  placeholder="Search"
                  aria-label="Search columns"
                  className="h-10 w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground"
                />
              </div>
              <ul className="flex-1 overflow-y-auto p-2">
                <li className="px-1 py-1 text-xs font-medium text-muted-foreground">
                  Reports
                </li>
                {available.length === 0 ? (
                  <li className="px-2 py-6 text-center text-sm text-muted-foreground">
                    No columns
                  </li>
                ) : (
                  available.map((col) => (
                    <li key={col.key}>
                      <button
                        type="button"
                        onClick={() =>
                          setActive({ list: "available", key: col.key })
                        }
                        onDoubleClick={() => {
                          setWorking((w) => addReportColumn(w, col.key));
                          setActive(null);
                        }}
                        className={itemClass(
                          active?.list === "available" &&
                            active.key === col.key
                        )}
                      >
                        {col.label}
                      </button>
                    </li>
                  ))
                )}
              </ul>
            </div>
          </div>

          {/* Move arrow (direction follows the highlighted side) */}
          <div className="flex items-center">
            <button
              type="button"
              onClick={moveActive}
              disabled={!active}
              aria-label={
                active?.list === "selected" ? "Remove column" : "Add column"
              }
              className="rounded-full border p-2 text-muted-foreground enabled:hover:bg-accent enabled:hover:text-foreground disabled:opacity-40"
            >
              <MoveIcon className="h-4 w-4" />
            </button>
          </div>

          {/* Selected */}
          <div className="space-y-2">
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Selected Columns
            </p>
            <div className="flex h-80 flex-col rounded-md border">
              <ul className="flex-1 overflow-y-auto p-2">
                {working.length === 0 ? (
                  <li className="px-2 py-6 text-center text-sm text-muted-foreground">
                    No columns selected
                  </li>
                ) : (
                  working.map((key) => (
                    <li key={key}>
                      <button
                        type="button"
                        onClick={() => setActive({ list: "selected", key })}
                        onDoubleClick={() => {
                          setWorking((w) => removeReportColumn(w, key));
                          setActive(null);
                        }}
                        className={itemClass(
                          active?.list === "selected" && active.key === key
                        )}
                      >
                        {reportColumnLabel(key)}
                      </button>
                    </li>
                  ))
                )}
              </ul>
            </div>
          </div>
        </div>

        <DialogFooter className="sm:justify-start">
          <Button
            type="button"
            onClick={() => {
              onExecute(working);
              onOpenChange(false);
            }}
          >
            Execute
          </Button>
          <Button
            type="button"
            variant="outline"
            onClick={() => onOpenChange(false)}
          >
            Cancel
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
