"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { db } from "@/lib/db";
import { requireOrganization } from "@/lib/auth-helpers";
import { writeAuditLog } from "@/lib/audit";

/**
 * Inline number-series editor — called from the settings-gear popover
 * next to the Quote#/Sales Order#/Invoice# display on each transaction
 * form. Per <quotes_spec>:
 *   "settings-gear icon that opens a popover: 'Auto-generate / Enter
 *    manually' radio + prefix/next number/padding inputs (writes to
 *    TransactionNumberSeries). Default auto-generate."
 *
 * Reuses the existing NumberSeries table (D40) — no schema change.
 */

const inputSchema = z.object({
  module: z.string().min(1).max(40),
  prefix: z.string().min(1).max(20),
  nextValue: z.coerce.number().int().min(1).max(99_999_999),
  padding: z.coerce.number().int().min(1).max(10),
  isAutoGenerated: z.boolean().default(true),
});
export type UpdateNumberSeriesInput = z.input<typeof inputSchema>;

export async function updateNumberSeriesInlineAction(
  input: UpdateNumberSeriesInput
): Promise<{ ok: true; preview: string }> {
  const { user, organization } = await requireOrganization();
  const data = inputSchema.parse(input);

  await db.numberSeries.upsert({
    where: {
      organizationId_module: {
        organizationId: organization.id,
        module: data.module,
      },
    },
    update: {
      prefix: data.prefix,
      nextValue: data.nextValue,
      padding: data.padding,
      isAutoGenerated: data.isAutoGenerated,
    },
    create: {
      organizationId: organization.id,
      module: data.module,
      prefix: data.prefix,
      nextValue: data.nextValue,
      padding: data.padding,
      isAutoGenerated: data.isAutoGenerated,
    },
  });

  await writeAuditLog({
    organizationId: organization.id,
    userId: user.id,
    action: "UPDATE",
    entityType: "NumberSeries",
    entityId: data.module,
    after: {
      prefix: data.prefix,
      nextValue: data.nextValue,
      padding: data.padding,
      isAutoGenerated: data.isAutoGenerated,
    },
  });

  revalidatePath(`/sales/${moduleToUrlSlug(data.module)}/new`);
  // Also revalidate the settings page so it stays in sync if the merchant
  // alternates between in-form and direct-settings editing.
  revalidatePath("/settings/number-series");

  const preview = `${data.prefix}${String(data.nextValue).padStart(data.padding, "0")}`;
  return { ok: true, preview };
}

function moduleToUrlSlug(m: string): string {
  switch (m) {
    case "quote":
      return "quotes";
    case "salesOrder":
      return "orders";
    case "invoice":
      return "invoices";
    case "creditNote":
      return "credit-notes";
    case "deliveryChallan":
      return "delivery-challans";
    case "paymentReceived":
      return "payments-received";
    case "recurringInvoice":
      return "recurring-invoices";
    default:
      return m;
  }
}
