import Link from "next/link";
import { ArrowLeft, X } from "lucide-react";
import { db } from "@/lib/db";
import { requireOrganization } from "@/lib/auth-helpers";
import { Button } from "@/components/ui/button";
import { InvoiceForm } from "../invoice-form";
import {
  createInvoiceAction,
  getBillableExpensesForCustomerAction,
} from "../actions";
import { peekNextDocumentNumber } from "@/lib/sales/numbering";
import type { InvoiceInput } from "@/lib/validations/invoice";

export const metadata = { title: "New Invoice" };

export default async function NewInvoicePage() {
  const { organization } = await requireOrganization();
  const [contacts, items, taxes, salespeople, paymentTerms, pdfTemplates, numberSeries, nextNumber, customFieldDefs] = await Promise.all([
    db.contact.findMany({
      where: {
        organizationId: organization.id,
        deletedAt: null,
        type: { in: ["CUSTOMER", "BOTH"] as ("CUSTOMER" | "BOTH")[] },
      },
      orderBy: { displayName: "asc" },
      select: { id: true, displayName: true, email: true, companyName: true },
    }),
    db.item.findMany({
      where: { organizationId: organization.id, deletedAt: null, isActive: true },
      orderBy: { name: "asc" },
      select: { id: true, name: true, sellingPrice: true, salesDescription: true, unit: true },
    }),
    db.tax.findMany({
      where: { organizationId: organization.id, isActive: true },
      orderBy: { rate: "asc" },
    }),
    db.salesperson.findMany({
      where: { organizationId: organization.id, isInactive: false },
      orderBy: { name: "asc" },
    }),
    db.paymentTerms.findMany({
      where: { organizationId: organization.id },
      orderBy: { numberOfDays: "asc" },
    }),
    db.pdfTemplate.findMany({
      where: { organizationId: organization.id, documentType: "INVOICE" },
      orderBy: { name: "asc" },
    }),
    db.numberSeries.findUnique({
      where: {
        organizationId_module: { organizationId: organization.id, module: "invoice" },
      },
    }),
    peekNextDocumentNumber(organization.id, "INVOICE"),
    db.customFieldDefinition.findMany({
      where: {
        organizationId: organization.id,
        entityType: "INVOICE",
        deletedAt: null,
      },
      orderBy: [{ position: "asc" }, { createdAt: "asc" }],
    }),
  ]);

  async function submit(values: InvoiceInput, opts?: { send?: boolean }) {
    "use server";
    await createInvoiceAction(values, opts);
  }

  return (
    <div className="p-6 max-w-6xl mx-auto space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Button asChild variant="ghost" size="icon" aria-label="Back">
            <Link href="/sales/invoices">
              <ArrowLeft className="h-4 w-4" />
            </Link>
          </Button>
          <h1 className="text-xl font-semibold">New Invoice</h1>
        </div>
        <Button asChild variant="ghost" size="icon" aria-label="Close">
          <Link href="/sales/invoices">
            <X className="h-4 w-4" />
          </Link>
        </Button>
      </div>
      <InvoiceForm
        nextNumber={nextNumber}
        defaultCurrency={organization.currency}
        contactOptions={contacts.map((c) => ({
          value: c.id,
          label: c.displayName,
          hint: c.email ?? c.companyName ?? undefined,
        }))}
        itemOptions={items.map((i) => ({
          value: i.id,
          label: i.name,
          rate: i.sellingPrice ? String(i.sellingPrice) : "0",
          description: i.salesDescription ?? undefined,
          unit: i.unit ?? undefined,
        }))}
        taxOptions={taxes.map((t) => ({
          value: t.id,
          label: `${t.name} (${Number(t.rate)}%)`,
          rate: Number(t.rate),
        }))}
        salespersonOptions={salespeople.map((s) => ({ value: s.id, label: s.name }))}
        paymentTermsOptions={paymentTerms.map((p) => ({
          value: p.id,
          label: p.name,
          numberOfDays: p.numberOfDays,
        }))}
        pdfTemplateOptions={pdfTemplates.map((t) => ({ value: t.id, label: t.name }))}
        customFieldDefinitions={customFieldDefs.map((d) => ({
          id: d.id,
          fieldKey: d.fieldKey,
          label: d.label,
          dataType: d.dataType as
            | "text"
            | "number"
            | "date"
            | "dropdown"
            | "checkbox"
            | "email"
            | "url",
          options:
            (d.options as { label: string; value: string }[] | null) ?? null,
          isRequired: d.isRequired,
        }))}
        numberSeries={
          numberSeries
            ? {
                prefix: numberSeries.prefix,
                nextValue: numberSeries.nextValue,
                padding: numberSeries.padding,
                isAutoGenerated: numberSeries.isAutoGenerated,
              }
            : { prefix: "INV-", nextValue: 1, padding: 5, isAutoGenerated: true }
        }
        onSubmitAction={submit}
        loadBillableExpensesAction={getBillableExpensesForCustomerAction}
        submitLabel="Save as Draft"
      />
    </div>
  );
}
