"use client";

import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Loader2, Repeat } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Combobox, type ComboboxOption } from "@/components/ui/combobox";
import { DatePicker } from "@/components/shared/date-picker";
import { MoneyInput } from "@/components/shared/money-input";
import {
  TransactionLineItemsTable,
  type LineItem,
  type ItemOption,
  type TaxOption,
} from "@/components/shared/transaction-line-items-table";
import { AttachFilesField, type AttachedFile } from "@/components/shared/attach-files-field";
import { PdfTemplatePicker } from "@/components/shared/pdf-template-picker";
import { CustomFieldsSection } from "@/components/shared/custom-fields-section";
import {
  BillableExpensesPanel,
  type BillableExpenseAdd,
} from "@/components/shared/billable-expenses-panel";
import type { BillableSource } from "@/lib/sales/billable-expenses";
import { NumberSeriesPopover } from "@/components/shared/number-series-popover";
import { updateNumberSeriesInlineAction } from "@/app/(dashboard)/settings/number-series/inline-actions";
import {
  createSalespersonInlineAction,
  createCustomerInlineAction,
  findItemBySkuAction,
} from "@/app/(dashboard)/sales/_inline-create/actions";
import type { InvoiceInput } from "@/lib/validations/invoice";
import { format } from "date-fns";
import { toast } from "sonner";

export type InvoiceFormProps = {
  initial?: Partial<InvoiceInput>;
  initialLines?: LineItem[];
  nextNumber: string;
  contactOptions: ComboboxOption[];
  itemOptions: ItemOption[];
  taxOptions: TaxOption[];
  salespersonOptions: ComboboxOption[];
  paymentTermsOptions: { value: string; label: string; numberOfDays: number }[];
  pdfTemplateOptions?: ComboboxOption[];
  numberSeries?: { prefix: string; nextValue: number; padding: number; isAutoGenerated: boolean };
  defaultCurrency: string;
  // M17c: optional Custom Fields wiring. Page server component fetches
  // active definitions for entityType=INVOICE; on edit it also passes
  // saved values keyed by fieldDefinitionId.
  customFieldDefinitions?: {
    id: string;
    fieldKey: string;
    label: string;
    dataType:
      | "text"
      | "number"
      | "date"
      | "dropdown"
      | "checkbox"
      | "email"
      | "url";
    options: { label: string; value: string }[] | null;
    isRequired: boolean;
  }[];
  customFieldInitialValues?: Record<string, unknown>;
  /**
   * M17e: when editing a saved invoice, pass its id so the bottom bar
   * shows a "Make Recurring" link → routes to
   * /sales/recurring-invoices/new?fromInvoiceId=<id>. Hidden on create.
   */
  existingInvoiceId?: string;
  /**
   * P9-A: when supplied, the form renders the BillableExpensesPanel
   * under the customer band and watches contactId for changes.
   * Returns Bill line items + Expense rows the customer owes back.
   */
  loadBillableExpensesAction?: (input: {
    customerId: string;
  }) => Promise<BillableSource[]>;
  onSubmitAction: (
    values: InvoiceInput,
    opts?: { send?: boolean }
  ) => Promise<unknown>;
  submitLabel?: string;
  cancelHref?: string;
};

function addDays(d: Date, n: number) {
  const r = new Date(d);
  r.setDate(r.getDate() + n);
  return r;
}

export function InvoiceForm({
  initial,
  initialLines,
  nextNumber,
  contactOptions,
  itemOptions,
  taxOptions,
  salespersonOptions,
  paymentTermsOptions,
  pdfTemplateOptions = [],
  numberSeries,
  defaultCurrency,
  customFieldDefinitions = [],
  customFieldInitialValues = {},
  existingInvoiceId,
  loadBillableExpensesAction,
  onSubmitAction,
  submitLabel = "Save as Draft",
  cancelHref = "/sales/invoices",
}: InvoiceFormProps) {
  const router = useRouter();
  const [busy, setBusy] = React.useState<"idle" | "draft" | "send">("idle");
  const [contactId, setContactId] = React.useState<string | null>(initial?.contactId ?? null);
  const [referenceNumber, setReferenceNumber] = React.useState(initial?.referenceNumber ?? "");
  const [invoiceDate, setInvoiceDate] = React.useState<Date>(
    initial?.invoiceDate ? new Date(initial.invoiceDate as unknown as string) : new Date()
  );
  const [paymentTermsId, setPaymentTermsId] = React.useState<string | null>(
    initial?.paymentTermsId ?? null
  );
  const [dueDate, setDueDate] = React.useState<Date>(
    initial?.dueDate ? new Date(initial.dueDate as unknown as string) : new Date()
  );
  const [salespersonId, setSalespersonId] = React.useState<string | null>(
    initial?.salespersonId ?? null
  );
  const [discountValue, setDiscountValue] = React.useState(
    String((initial?.documentDiscount?.value as number | undefined) ?? "0")
  );
  const [discountType, setDiscountType] = React.useState<"percentage" | "amount">(
    initial?.documentDiscount?.type ?? "percentage"
  );
  const [adjustmentLabel, setAdjustmentLabel] = React.useState(
    initial?.adjustmentLabel ?? "Adjustment"
  );
  const [adjustmentValue, setAdjustmentValue] = React.useState(
    String((initial?.adjustmentValue as number | undefined) ?? "0")
  );
  // M17a: default customer notes to "Thanks for your business." per the
  // Invoices Refinement Patch. Edit pages preserve whatever the user saved.
  const [customerNotes, setCustomerNotes] = React.useState(
    initial?.customerNotes ?? (initial ? "" : "Thanks for your business.")
  );
  const [terms, setTerms] = React.useState(initial?.termsAndConditions ?? "");
  const [pdfTemplateId, setPdfTemplateId] = React.useState<string | null>(
    initial?.pdfTemplateId ?? null
  );
  const [attachments, setAttachments] = React.useState<AttachedFile[]>(
    (initial?.attachments as AttachedFile[] | undefined) ?? []
  );
  const [contactsState, setContactsState] = React.useState(contactOptions);
  const [salespeopleState, setSalespeopleState] = React.useState(salespersonOptions);
  const [lines, setLines] = React.useState<LineItem[]>(initialLines ?? []);

  // P9-A: Billable-expenses tracking.
  //
  //   - `lineTableKey` bumps every time we inject billable lines so
  //     <TransactionLineItemsTable> remounts with the merged
  //     `linesSeed` as initialLines. Without the key change, the
  //     table's internal useState keeps the old line list.
  //   - `linesSeed` holds the canonical line list including any
  //     billable additions — `initialLines` for the next remount.
  //   - `billableSources` collects {type,id,amount,invoiceLineIndex}
  //     records for every billable item the user pulled in. The
  //     save action consumes this to mark the source rows used.
  const [lineTableKey, setLineTableKey] = React.useState(0);
  const [linesSeed, setLinesSeed] = React.useState<LineItem[]>(
    initialLines ?? []
  );
  const [billableSources, setBillableSources] = React.useState<
    InvoiceInput["billableSources"]
  >([]);

  // M17c: Custom Fields state — keyed by fieldDefinitionId
  const [customFieldValues, setCustomFieldValues] = React.useState<
    Record<string, unknown>
  >(customFieldInitialValues);

  /**
   * P9-A: handler for <BillableExpensesPanel>. Merges new lines into
   * `linesSeed`, bumps the table key so the table remounts with
   * those lines pre-populated, and records {type,id,amount,index}
   * tuples in billableSources for the save action to consume.
   *
   * Known v1 limitation: if the user deletes one of the injected
   * billable lines before saving, the source still gets marked used.
   * The BillableExpenseUsage unique index prevents double-billing on
   * the next attempt, but the source row's `billableUsedAt`/
   * `isBilled` flag remains set. Real-world impact is small; revisit
   * once we have a stable LineItem identifier across table remounts.
   */
  const addBillableLines = React.useCallback(
    (adds: BillableExpenseAdd[]) => {
      const baseLines = lines.length > 0 ? lines : linesSeed;
      const offset = baseLines.length;
      const newLines: LineItem[] = adds.map((a, i) => ({
        id: `billable-${Date.now()}-${i}`,
        itemId: null,
        name: a.line.name,
        description: a.line.description,
        accountId: a.line.accountId,
        quantity: a.line.quantity,
        rate: a.line.rate,
      }));
      const merged = [...baseLines, ...newLines];
      setLinesSeed(merged);
      setLines(merged);
      setLineTableKey((k) => k + 1);
      setBillableSources((prev) => [
        ...(prev ?? []),
        ...adds.map((a, i) => ({
          type: a.source.type,
          id: a.source.id,
          amount: a.source.amount,
          invoiceLineIndex: offset + i,
        })),
      ]);
    },
    [lines, linesSeed]
  );

  // When payment terms change, recompute due date from invoice date.
  React.useEffect(() => {
    if (!paymentTermsId) return;
    const term = paymentTermsOptions.find((p) => p.value === paymentTermsId);
    if (!term) return;
    setDueDate(addDays(invoiceDate, term.numberOfDays));
  }, [paymentTermsId, invoiceDate, paymentTermsOptions]);

  async function submit(send: boolean) {
    if (!contactId) {
      toast.error("Pick a customer");
      return;
    }
    if (lines.length === 0 || lines.every((l) => !l.name)) {
      toast.error("Add at least one line item");
      return;
    }
    setBusy(send ? "send" : "draft");
    const payload: InvoiceInput = {
      contactId,
      referenceNumber: referenceNumber || null,
      invoiceDate: format(invoiceDate, "yyyy-MM-dd") as unknown as Date,
      dueDate: format(dueDate, "yyyy-MM-dd") as unknown as Date,
      paymentTermsId,
      salespersonId,
      projectId: null,
      status: send ? "SENT" : "DRAFT",
      currency: defaultCurrency,
      documentDiscount: { value: Number(discountValue || 0), type: discountType },
      adjustmentLabel,
      adjustmentValue: Number(adjustmentValue || 0),
      customerNotes,
      termsAndConditions: terms || null,
      pdfTemplateId,
      attachments,
      lines: lines
        .filter((l) => l.name.trim())
        .map((l, i) => ({
          itemId: l.itemId ?? null,
          position: i,
          name: l.name,
          description: l.description ?? null,
          hsnSacCode: l.hsnSacCode ?? null,
          quantity: Number(l.quantity || 0),
          unit: l.unit ?? null,
          rate: Number(l.rate || 0),
          discount: Number(l.discount || 0),
          discountType: l.discountType ?? "percentage",
          taxId: l.taxId ?? null,
        })),
      // M17c: include any populated custom-field values
      customFieldValues: Object.entries(customFieldValues)
        .filter(([, v]) => v !== undefined && v !== null && v !== "")
        .map(([fieldDefinitionId, value]) => ({
          fieldDefinitionId,
          value,
        })),
      // P9-A: billable-expense sources to mark used on save.
      billableSources: billableSources ?? [],
    };
    try {
      await onSubmitAction(payload, { send });
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Save failed");
      setBusy("idle");
    }
  }

  return (
    <div className="space-y-6">
      <section className="rounded-md border bg-card p-6 grid gap-4 md:grid-cols-[10rem_1fr]">
        <Label className="pt-2">Customer Name *</Label>
        <Combobox
          options={contactsState}
          value={contactId}
          onChange={setContactId}
          placeholder="Select customer…"
          allowCreate
          onCreate={async (input: string) => {
            try {
              const created = await createCustomerInlineAction({
                displayName: input,
                email: null,
              });
              setContactsState((prev) => [
                ...prev,
                { value: created.id, label: created.displayName },
              ]);
              setContactId(created.id);
            } catch (err) {
              toast.error(err instanceof Error ? err.message : "Couldn't add customer");
            }
          }}
        />

        <Label className="pt-2">Invoice #</Label>
        {!initial && numberSeries ? (
          <NumberSeriesPopover
            module="invoice"
            current={nextNumber}
            prefix={numberSeries.prefix}
            nextValue={numberSeries.nextValue}
            padding={numberSeries.padding}
            isAutoGenerated={numberSeries.isAutoGenerated}
            action={updateNumberSeriesInlineAction}
          />
        ) : (
          <Input value={initial ? "(unchanged)" : nextNumber} disabled className="font-mono" />
        )}

        <Label className="pt-2">Order Number</Label>
        <Input
          value={referenceNumber ?? ""}
          onChange={(e) => setReferenceNumber(e.target.value)}
          placeholder="Optional"
        />

        <Label className="pt-2">Invoice Date *</Label>
        <DatePicker value={invoiceDate} onChange={(d) => d && setInvoiceDate(d)} />

        <Label className="pt-2">Payment Terms</Label>
        <Combobox
          options={paymentTermsOptions.map((p) => ({ value: p.value, label: p.label }))}
          value={paymentTermsId}
          onChange={setPaymentTermsId}
          placeholder="Due on Receipt"
        />

        <Label className="pt-2">Due Date *</Label>
        <DatePicker value={dueDate} onChange={(d) => d && setDueDate(d)} />

        <Label className="pt-2">Salesperson</Label>
        <Combobox
          options={salespeopleState}
          value={salespersonId}
          onChange={setSalespersonId}
          placeholder="Optional"
          allowCreate
          onCreate={async (input: string) => {
            try {
              const created = await createSalespersonInlineAction({ name: input });
              setSalespeopleState((prev) => [
                ...prev,
                { value: created.id, label: created.name },
              ]);
              setSalespersonId(created.id);
            } catch (err) {
              toast.error(err instanceof Error ? err.message : "Couldn't add salesperson");
            }
          }}
        />
      </section>

      {/* P9-A: Billable-expense banner + picker. Renders only when
          a customer is selected AND the page server passed
          `loadBillableExpensesAction`. */}
      {loadBillableExpensesAction ? (
        <BillableExpensesPanel
          customerId={contactId}
          currency={defaultCurrency}
          loadAction={loadBillableExpensesAction}
          onAddLines={addBillableLines}
        />
      ) : null}

      <TransactionLineItemsTable
        key={`lt-${lineTableKey}`}
        itemOptions={itemOptions}
        taxOptions={taxOptions}
        documentDiscount={{ value: discountValue, type: discountType }}
        adjustment={adjustmentValue}
        onChange={(ls) => setLines(ls)}
        initialLines={lineTableKey === 0 ? initialLines : linesSeed}
        scanItemAction={findItemBySkuAction}
      />

      {customFieldDefinitions.length > 0 ? (
        <CustomFieldsSection
          entityType="INVOICE"
          definitions={customFieldDefinitions}
          values={customFieldValues}
          onChange={setCustomFieldValues}
          defaultOpen
        />
      ) : null}

      <section className="grid gap-4 md:grid-cols-2">
        <div className="space-y-3">
          <Label htmlFor="customer-notes">Customer Notes</Label>
          <Textarea
            id="customer-notes"
            value={customerNotes ?? ""}
            onChange={(e) => setCustomerNotes(e.target.value)}
            rows={3}
          />
          <p className="text-xs text-muted-foreground">
            Will be displayed on the invoice
          </p>
          <Label htmlFor="terms">Terms &amp; Conditions</Label>
          <Textarea id="terms" value={terms ?? ""} onChange={(e) => setTerms(e.target.value)} rows={3} />
        </div>
        <div className="rounded-md border p-4 space-y-3 text-sm">
          <div className="flex items-center justify-between gap-2">
            <Label>Document discount</Label>
            <div className="flex items-center gap-1">
              <MoneyInput value={discountValue} onChange={setDiscountValue} />
              <select
                value={discountType}
                onChange={(e) => setDiscountType(e.target.value as "percentage" | "amount")}
                className="h-10 rounded border px-2 bg-background"
                aria-label="Discount type"
              >
                <option value="percentage">%</option>
                <option value="amount">{defaultCurrency}</option>
              </select>
            </div>
          </div>
          <div className="flex items-center justify-between gap-2">
            <Input
              value={adjustmentLabel ?? ""}
              onChange={(e) => setAdjustmentLabel(e.target.value)}
              className="max-w-[10rem]"
            />
            <MoneyInput value={adjustmentValue} onChange={setAdjustmentValue} allowNegative />
          </div>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-2">
        <div>
          <AttachFilesField
            initial={attachments}
            onChange={setAttachments}
            maxFiles={10}
            maxSizeMb={10}
            label="Attach files to Invoice"
          />
        </div>
        {pdfTemplateOptions.length > 0 ? (
          <PdfTemplatePicker
            templates={pdfTemplateOptions}
            value={pdfTemplateId}
            onChange={setPdfTemplateId}
          />
        ) : null}
      </section>

      <div className="flex items-center gap-2 sticky bottom-0 bg-background border-t -mx-6 px-6 py-3">
        <Button type="button" onClick={() => submit(false)} disabled={busy !== "idle"} className="gap-1">
          {busy === "draft" ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
          {submitLabel}
        </Button>
        <Button type="button" variant="outline" onClick={() => submit(true)} disabled={busy !== "idle"} className="gap-1">
          {busy === "send" ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
          Save and Send
        </Button>
        <Button type="button" variant="ghost" onClick={() => router.push(cancelHref)}>
          Cancel
        </Button>
        {existingInvoiceId ? (
          <Link
            href={`/sales/recurring-invoices/new?fromInvoiceId=${existingInvoiceId}`}
            className={cn(
              "ml-auto inline-flex items-center gap-1 text-sm text-primary hover:underline",
              lines.length === 0 || lines.every((l) => !l.name.trim())
                ? "pointer-events-none opacity-50"
                : ""
            )}
            aria-disabled={
              lines.length === 0 || lines.every((l) => !l.name.trim())
            }
          >
            <Repeat className="h-4 w-4" />
            Make Recurring
          </Link>
        ) : null}
      </div>
    </div>
  );
}
