import { redirect } from "next/navigation";
import { requireOrganization } from "@/lib/auth-helpers";
import { db } from "@/lib/db";
import { findReport } from "@/lib/reports/catalog";
import { buildCustomReportStructure } from "@/lib/reports/custom-report-structure";
import { CustomReportWizard } from "../custom-report-wizard";

export const metadata = { title: "Create Custom Report" };

/**
 * REPORTS — "Create Custom Report" wizard entry page.
 *
 * Reached from the Reports Center modal: the user picks a base report
 * and clicks Proceed, which navigates here with `?base=<reportKey>`.
 * We resolve that key against the static catalog and hand off to the
 * client wizard. Missing/unknown base → bounce back to /reports.
 *
 * For P&L-family bases we also load the org's Chart of Accounts and
 * build the Step 2 ("Customize Rows and Columns") structural tree:
 * accounts grouped into the standard P&L sections, interleaved with the
 * formula subtotal rows. `buildCustomReportStructure` returns `null` for
 * report types without a structure editor yet — the wizard then shows a
 * "coming soon" message. The COA read is fail-open: any error just
 * yields `structure = null` so the wizard still renders and navigates.
 *
 * `requireOrganization()` gates access (auth + org scope).
 */
export default async function NewCustomReportPage({
  searchParams,
}: {
  searchParams?: { base?: string };
}) {
  const { user, organization } = await requireOrganization();

  const base = searchParams?.base ? findReport(searchParams.base) : undefined;
  if (!base) {
    redirect("/reports");
  }

  // Org details lines (address, country, email) — shown in the Step 3
  // Preview when "Organization Details" is toggled on. Map "IN" → "India",
  // otherwise keep the raw code.
  const countryName =
    organization.country === "IN" ? "India" : organization.country;
  const orgDetailsLines: string[] = [
    organization.address,
    countryName,
    organization.email,
  ].filter((s): s is string => Boolean(s && s.trim()));

  // First name (or local-part of email) — shown in the Step 3 Preview
  // footer under "Generated By".
  const userFirstName =
    user.name?.trim().split(" ")[0] ??
    user.email?.split("@")[0]?.split(".")[0] ??
    null;

  let structure: ReturnType<typeof buildCustomReportStructure> = null;
  try {
    const accounts = await db.chartOfAccount.findMany({
      where: { organizationId: organization.id, isActive: true },
      select: { id: true, name: true, code: true, type: true },
      orderBy: [{ code: "asc" }, { name: "asc" }],
    });
    structure = buildCustomReportStructure(
      base.key,
      accounts.map((a) => ({
        id: a.id,
        name: a.name,
        code: a.code,
        type: String(a.type),
      })),
    );
  } catch {
    structure = null;
  }

  return (
    <CustomReportWizard
      baseKey={base.key}
      baseName={base.name}
      baseHref={base.href ?? null}
      structure={structure}
      orgName={organization.name}
      orgDetailsLines={orgDetailsLines}
      userFirstName={userFirstName}
    />
  );
}
