-- CreateEnum
CREATE TYPE "CustomerType" AS ENUM ('BUSINESS', 'INDIVIDUAL');

-- CreateEnum
CREATE TYPE "QuoteStatus" AS ENUM ('DRAFT', 'SENT', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'INVOICED');

-- CreateEnum
CREATE TYPE "SalesOrderStatus" AS ENUM ('DRAFT', 'CONFIRMED', 'CLOSED', 'VOID');

-- AlterEnum
ALTER TYPE "InvoiceStatus" ADD VALUE 'WRITTEN_OFF';

-- AlterTable
ALTER TABLE "Contact" ADD COLUMN     "accountsPayableId" TEXT,
ADD COLUMN     "accountsReceivableId" TEXT,
ADD COLUMN     "customerOwnerId" TEXT,
ADD COLUMN     "customerType" "CustomerType" NOT NULL DEFAULT 'BUSINESS',
ADD COLUMN     "enablePortal" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "facebookUrl" TEXT,
ADD COLUMN     "firstName" TEXT,
ADD COLUMN     "gstTreatment" TEXT,
ADD COLUMN     "gstin" TEXT,
ADD COLUMN     "isInactive" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "language" TEXT NOT NULL DEFAULT 'en',
ADD COLUMN     "lastName" TEXT,
ADD COLUMN     "mobile" TEXT,
ADD COLUMN     "mobileCountry" TEXT DEFAULT '+91',
ADD COLUMN     "openingBalance" DECIMAL(18,4),
ADD COLUMN     "openingBalanceAsOf" TIMESTAMP(3),
ADD COLUMN     "pan" TEXT,
ADD COLUMN     "paymentTermsId" TEXT,
ADD COLUMN     "placeOfSupply" TEXT,
ADD COLUMN     "portalLanguage" TEXT,
ADD COLUMN     "salutation" TEXT,
ADD COLUMN     "taxPreference" TEXT,
ADD COLUMN     "twitterHandle" TEXT,
ADD COLUMN     "websiteUrl" TEXT,
ADD COLUMN     "workPhone" TEXT,
ADD COLUMN     "workPhoneCountry" TEXT DEFAULT '+91';

-- AlterTable
ALTER TABLE "CreditNote" ADD COLUMN     "amountApplied" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "amountRefunded" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'INR',
ADD COLUMN     "customerNotes" TEXT,
ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "pdfTemplateId" TEXT,
ADD COLUMN     "referenceNumber" TEXT,
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'OPEN',
ADD COLUMN     "subTotal" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "taxAmount" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "termsAndConditions" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "DeliveryChallan" ADD COLUMN     "challanType" TEXT NOT NULL DEFAULT 'others',
ADD COLUMN     "customerNotes" TEXT,
ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "pdfTemplateId" TEXT,
ADD COLUMN     "referenceNumber" TEXT,
ADD COLUMN     "termsAndConditions" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "status" SET DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "adjustmentLabel" TEXT DEFAULT 'Adjustment',
ADD COLUMN     "adjustmentValue" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "customerNotes" TEXT,
ADD COLUMN     "discountType" TEXT NOT NULL DEFAULT 'percentage',
ADD COLUMN     "discountValue" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "paymentTermsId" TEXT,
ADD COLUMN     "pdfTemplateId" TEXT,
ADD COLUMN     "portalAccessToken" TEXT NOT NULL,
ADD COLUMN     "projectId" TEXT,
ADD COLUMN     "recurringInvoiceId" TEXT,
ADD COLUMN     "referenceNumber" TEXT,
ADD COLUMN     "salespersonId" TEXT,
ADD COLUMN     "sentAt" TIMESTAMP(3),
ADD COLUMN     "taxId" TEXT,
ADD COLUMN     "taxType" TEXT,
ADD COLUMN     "termsAndConditions" TEXT,
ADD COLUMN     "voidedAt" TIMESTAMP(3),
ADD COLUMN     "writtenOffAmount" DECIMAL(18,4),
ADD COLUMN     "writtenOffAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "NumberSeries" ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "resetOnFiscalYear" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "PaymentReceived" ADD COLUMN     "amountInExcess" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "amountUsedForInvoices" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "bankCharges" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "depositToAccountId" TEXT,
ADD COLUMN     "paymentMode" TEXT DEFAULT 'bank_transfer',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Quote" ADD COLUMN     "acceptedAt" TIMESTAMP(3),
ADD COLUMN     "adjustmentLabel" TEXT DEFAULT 'Adjustment',
ADD COLUMN     "adjustmentValue" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "convertedInvoiceId" TEXT,
ADD COLUMN     "convertedSalesOrderId" TEXT,
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'INR',
ADD COLUMN     "customerNotes" TEXT,
ADD COLUMN     "declinedAt" TIMESTAMP(3),
ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "discountType" TEXT NOT NULL DEFAULT 'percentage',
ADD COLUMN     "discountValue" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "pdfTemplateId" TEXT,
ADD COLUMN     "projectId" TEXT,
ADD COLUMN     "referenceNumber" TEXT,
ADD COLUMN     "salespersonId" TEXT,
ADD COLUMN     "sentAt" TIMESTAMP(3),
ADD COLUMN     "subTotal" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "subject" TEXT,
ADD COLUMN     "taxAmount" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "taxId" TEXT,
ADD COLUMN     "taxType" TEXT,
ADD COLUMN     "termsAndConditions" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL,
DROP COLUMN "status",
ADD COLUMN     "status" "QuoteStatus" NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE "RecurringInvoice" ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "emailAutomatically" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "endDate" TIMESTAMP(3),
ADD COLUMN     "intervalN" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "neverExpires" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "nextOccurrenceDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "occurrencesGenerated" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN     "templateJson" JSONB,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "SalesOrder" ADD COLUMN     "adjustmentLabel" TEXT DEFAULT 'Adjustment',
ADD COLUMN     "adjustmentValue" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "convertedInvoiceId" TEXT,
ADD COLUMN     "convertedPurchaseOrderId" TEXT,
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'INR',
ADD COLUMN     "customerNotes" TEXT,
ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "deliveryMethodId" TEXT,
ADD COLUMN     "discountType" TEXT NOT NULL DEFAULT 'percentage',
ADD COLUMN     "discountValue" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "expectedShipmentDate" TIMESTAMP(3),
ADD COLUMN     "paymentTermsId" TEXT,
ADD COLUMN     "pdfTemplateId" TEXT,
ADD COLUMN     "referenceNumber" TEXT,
ADD COLUMN     "salespersonId" TEXT,
ADD COLUMN     "subTotal" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "taxAmount" DECIMAL(18,4) NOT NULL DEFAULT 0,
ADD COLUMN     "taxId" TEXT,
ADD COLUMN     "taxType" TEXT,
ADD COLUMN     "termsAndConditions" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL,
DROP COLUMN "status",
ADD COLUMN     "status" "SalesOrderStatus" NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE "Tax" ADD COLUMN     "isDefault" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE "ContactAddress" (
    "id" TEXT NOT NULL,
    "contactId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "attention" TEXT,
    "country" TEXT NOT NULL DEFAULT 'India',
    "addressLine1" TEXT,
    "addressLine2" TEXT,
    "city" TEXT,
    "state" TEXT,
    "zipCode" TEXT,
    "phone" TEXT,
    "fax" TEXT,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "ContactAddress_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContactPerson" (
    "id" TEXT NOT NULL,
    "contactId" TEXT NOT NULL,
    "salutation" TEXT,
    "firstName" TEXT,
    "lastName" TEXT,
    "email" TEXT,
    "workPhone" TEXT,
    "mobile" TEXT,
    "designation" TEXT,
    "department" TEXT,
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "ContactPerson_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContactDocument" (
    "id" TEXT NOT NULL,
    "contactId" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "fileUrl" TEXT NOT NULL,
    "fileSize" INTEGER NOT NULL,
    "mimeType" TEXT NOT NULL,
    "uploadedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ContactDocument_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContactReportingTag" (
    "id" TEXT NOT NULL,
    "contactId" TEXT NOT NULL,
    "reportingTagOptionId" TEXT NOT NULL,

    CONSTRAINT "ContactReportingTag_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContactCustomField" (
    "id" TEXT NOT NULL,
    "contactId" TEXT NOT NULL,
    "fieldKey" TEXT NOT NULL,
    "value" JSONB,

    CONSTRAINT "ContactCustomField_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContactRemark" (
    "id" TEXT NOT NULL,
    "contactId" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "authorId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ContactRemark_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "InvoiceAttachment" (
    "id" TEXT NOT NULL,
    "invoiceId" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "fileUrl" TEXT NOT NULL,
    "fileSize" INTEGER NOT NULL,
    "mimeType" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "InvoiceAttachment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "InvoiceReminder" (
    "id" TEXT NOT NULL,
    "invoiceId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "daysOffset" INTEGER NOT NULL DEFAULT 0,
    "sentAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "InvoiceReminder_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "QuoteLineItem" (
    "id" TEXT NOT NULL,
    "quoteId" TEXT NOT NULL,
    "itemId" TEXT,
    "position" INTEGER NOT NULL DEFAULT 0,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "hsnSacCode" TEXT,
    "quantity" DECIMAL(18,4) NOT NULL,
    "unit" TEXT,
    "rate" DECIMAL(18,4) NOT NULL,
    "discount" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "discountType" TEXT NOT NULL DEFAULT 'percentage',
    "taxId" TEXT,
    "taxAmount" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "amount" DECIMAL(18,4) NOT NULL,

    CONSTRAINT "QuoteLineItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "QuoteAttachment" (
    "id" TEXT NOT NULL,
    "quoteId" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "fileUrl" TEXT NOT NULL,
    "fileSize" INTEGER NOT NULL,
    "mimeType" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "QuoteAttachment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "QuoteReportingTag" (
    "id" TEXT NOT NULL,
    "quoteId" TEXT NOT NULL,
    "reportingTagOptionId" TEXT NOT NULL,

    CONSTRAINT "QuoteReportingTag_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SalesOrderLineItem" (
    "id" TEXT NOT NULL,
    "salesOrderId" TEXT NOT NULL,
    "itemId" TEXT,
    "position" INTEGER NOT NULL DEFAULT 0,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "hsnSacCode" TEXT,
    "quantity" DECIMAL(18,4) NOT NULL,
    "unit" TEXT,
    "rate" DECIMAL(18,4) NOT NULL,
    "discount" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "discountType" TEXT NOT NULL DEFAULT 'percentage',
    "taxId" TEXT,
    "taxAmount" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "amount" DECIMAL(18,4) NOT NULL,

    CONSTRAINT "SalesOrderLineItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SalesOrderAttachment" (
    "id" TEXT NOT NULL,
    "salesOrderId" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "fileUrl" TEXT NOT NULL,
    "fileSize" INTEGER NOT NULL,
    "mimeType" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SalesOrderAttachment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DeliveryChallanLineItem" (
    "id" TEXT NOT NULL,
    "challanId" TEXT NOT NULL,
    "itemId" TEXT,
    "position" INTEGER NOT NULL DEFAULT 0,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "hsnSacCode" TEXT,
    "quantity" DECIMAL(18,4) NOT NULL,
    "unit" TEXT,
    "rate" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "discount" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "discountType" TEXT NOT NULL DEFAULT 'percentage',
    "taxId" TEXT,
    "taxAmount" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "amount" DECIMAL(18,4) NOT NULL DEFAULT 0,

    CONSTRAINT "DeliveryChallanLineItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DeliveryChallanAttachment" (
    "id" TEXT NOT NULL,
    "challanId" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "fileUrl" TEXT NOT NULL,
    "fileSize" INTEGER NOT NULL,
    "mimeType" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DeliveryChallanAttachment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecurringInvoiceOccurrence" (
    "id" TEXT NOT NULL,
    "recurringInvoiceId" TEXT NOT NULL,
    "occurrenceDate" TIMESTAMP(3) NOT NULL,
    "invoiceId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'GENERATED',
    "errorMessage" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecurringInvoiceOccurrence_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CreditNoteLineItem" (
    "id" TEXT NOT NULL,
    "creditNoteId" TEXT NOT NULL,
    "itemId" TEXT,
    "position" INTEGER NOT NULL DEFAULT 0,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "hsnSacCode" TEXT,
    "quantity" DECIMAL(18,4) NOT NULL,
    "unit" TEXT,
    "rate" DECIMAL(18,4) NOT NULL,
    "discount" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "discountType" TEXT NOT NULL DEFAULT 'percentage',
    "taxId" TEXT,
    "taxAmount" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "amount" DECIMAL(18,4) NOT NULL,

    CONSTRAINT "CreditNoteLineItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CreditNoteApplication" (
    "id" TEXT NOT NULL,
    "creditNoteId" TEXT NOT NULL,
    "invoiceId" TEXT NOT NULL,
    "amountApplied" DECIMAL(18,4) NOT NULL,
    "appliedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CreditNoteApplication_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CreditNoteRefund" (
    "id" TEXT NOT NULL,
    "creditNoteId" TEXT NOT NULL,
    "refundDate" TIMESTAMP(3) NOT NULL,
    "amount" DECIMAL(18,4) NOT NULL,
    "mode" TEXT NOT NULL,
    "reference" TEXT,
    "fromAccountId" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CreditNoteRefund_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PaymentTerms" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "numberOfDays" INTEGER NOT NULL,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "PaymentTerms_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DeliveryMethod" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "isInactive" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "DeliveryMethod_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Salesperson" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT,
    "isInactive" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "Salesperson_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PdfTemplate" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "documentType" TEXT NOT NULL,
    "configJson" JSONB NOT NULL,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "PdfTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EmailJob" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "toEmail" TEXT NOT NULL,
    "ccEmails" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "subject" TEXT NOT NULL,
    "bodyHtml" TEXT NOT NULL,
    "attachmentUrl" TEXT,
    "documentType" TEXT,
    "documentId" TEXT,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "lastError" TEXT,
    "scheduledFor" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "sentAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "EmailJob_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ContactAddress_contactId_kind_idx" ON "ContactAddress"("contactId", "kind");

-- CreateIndex
CREATE INDEX "ContactPerson_contactId_idx" ON "ContactPerson"("contactId");

-- CreateIndex
CREATE INDEX "ContactDocument_contactId_idx" ON "ContactDocument"("contactId");

-- CreateIndex
CREATE INDEX "ContactReportingTag_contactId_idx" ON "ContactReportingTag"("contactId");

-- CreateIndex
CREATE UNIQUE INDEX "ContactCustomField_contactId_fieldKey_key" ON "ContactCustomField"("contactId", "fieldKey");

-- CreateIndex
CREATE INDEX "ContactRemark_contactId_createdAt_idx" ON "ContactRemark"("contactId", "createdAt");

-- CreateIndex
CREATE INDEX "InvoiceAttachment_invoiceId_idx" ON "InvoiceAttachment"("invoiceId");

-- CreateIndex
CREATE INDEX "InvoiceReminder_invoiceId_idx" ON "InvoiceReminder"("invoiceId");

-- CreateIndex
CREATE INDEX "QuoteLineItem_quoteId_idx" ON "QuoteLineItem"("quoteId");

-- CreateIndex
CREATE INDEX "QuoteAttachment_quoteId_idx" ON "QuoteAttachment"("quoteId");

-- CreateIndex
CREATE INDEX "QuoteReportingTag_quoteId_idx" ON "QuoteReportingTag"("quoteId");

-- CreateIndex
CREATE INDEX "SalesOrderLineItem_salesOrderId_idx" ON "SalesOrderLineItem"("salesOrderId");

-- CreateIndex
CREATE INDEX "SalesOrderAttachment_salesOrderId_idx" ON "SalesOrderAttachment"("salesOrderId");

-- CreateIndex
CREATE INDEX "DeliveryChallanLineItem_challanId_idx" ON "DeliveryChallanLineItem"("challanId");

-- CreateIndex
CREATE INDEX "DeliveryChallanAttachment_challanId_idx" ON "DeliveryChallanAttachment"("challanId");

-- CreateIndex
CREATE INDEX "RecurringInvoiceOccurrence_recurringInvoiceId_idx" ON "RecurringInvoiceOccurrence"("recurringInvoiceId");

-- CreateIndex
CREATE UNIQUE INDEX "RecurringInvoiceOccurrence_recurringInvoiceId_occurrenceDat_key" ON "RecurringInvoiceOccurrence"("recurringInvoiceId", "occurrenceDate");

-- CreateIndex
CREATE INDEX "CreditNoteLineItem_creditNoteId_idx" ON "CreditNoteLineItem"("creditNoteId");

-- CreateIndex
CREATE UNIQUE INDEX "CreditNoteApplication_creditNoteId_invoiceId_key" ON "CreditNoteApplication"("creditNoteId", "invoiceId");

-- CreateIndex
CREATE INDEX "CreditNoteRefund_creditNoteId_idx" ON "CreditNoteRefund"("creditNoteId");

-- CreateIndex
CREATE UNIQUE INDEX "PaymentTerms_organizationId_name_key" ON "PaymentTerms"("organizationId", "name");

-- CreateIndex
CREATE UNIQUE INDEX "DeliveryMethod_organizationId_name_key" ON "DeliveryMethod"("organizationId", "name");

-- CreateIndex
CREATE INDEX "Salesperson_organizationId_isInactive_idx" ON "Salesperson"("organizationId", "isInactive");

-- CreateIndex
CREATE INDEX "PdfTemplate_organizationId_documentType_idx" ON "PdfTemplate"("organizationId", "documentType");

-- CreateIndex
CREATE INDEX "EmailJob_organizationId_status_scheduledFor_idx" ON "EmailJob"("organizationId", "status", "scheduledFor");

-- CreateIndex
CREATE INDEX "Contact_organizationId_isInactive_idx" ON "Contact"("organizationId", "isInactive");

-- CreateIndex
CREATE INDEX "CreditNote_organizationId_status_deletedAt_idx" ON "CreditNote"("organizationId", "status", "deletedAt");

-- CreateIndex
CREATE INDEX "DeliveryChallan_organizationId_status_deletedAt_idx" ON "DeliveryChallan"("organizationId", "status", "deletedAt");

-- CreateIndex
CREATE UNIQUE INDEX "Invoice_portalAccessToken_key" ON "Invoice"("portalAccessToken");

-- CreateIndex
CREATE INDEX "Invoice_organizationId_contactId_status_idx" ON "Invoice"("organizationId", "contactId", "status");

-- CreateIndex
CREATE INDEX "PaymentReceived_organizationId_paymentDate_idx" ON "PaymentReceived"("organizationId", "paymentDate");

-- CreateIndex
CREATE INDEX "PaymentReceived_organizationId_contactId_idx" ON "PaymentReceived"("organizationId", "contactId");

-- CreateIndex
CREATE UNIQUE INDEX "PaymentReceivedAllocation_paymentReceivedId_invoiceId_key" ON "PaymentReceivedAllocation"("paymentReceivedId", "invoiceId");

-- CreateIndex
CREATE INDEX "Quote_organizationId_status_deletedAt_idx" ON "Quote"("organizationId", "status", "deletedAt");

-- CreateIndex
CREATE INDEX "RecurringInvoice_organizationId_status_nextOccurrenceDate_idx" ON "RecurringInvoice"("organizationId", "status", "nextOccurrenceDate");

-- CreateIndex
CREATE INDEX "SalesOrder_organizationId_status_deletedAt_idx" ON "SalesOrder"("organizationId", "status", "deletedAt");

-- AddForeignKey
ALTER TABLE "ContactAddress" ADD CONSTRAINT "ContactAddress_contactId_fkey" FOREIGN KEY ("contactId") REFERENCES "Contact"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ContactPerson" ADD CONSTRAINT "ContactPerson_contactId_fkey" FOREIGN KEY ("contactId") REFERENCES "Contact"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ContactDocument" ADD CONSTRAINT "ContactDocument_contactId_fkey" FOREIGN KEY ("contactId") REFERENCES "Contact"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ContactReportingTag" ADD CONSTRAINT "ContactReportingTag_contactId_fkey" FOREIGN KEY ("contactId") REFERENCES "Contact"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ContactCustomField" ADD CONSTRAINT "ContactCustomField_contactId_fkey" FOREIGN KEY ("contactId") REFERENCES "Contact"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ContactRemark" ADD CONSTRAINT "ContactRemark_contactId_fkey" FOREIGN KEY ("contactId") REFERENCES "Contact"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_recurringInvoiceId_fkey" FOREIGN KEY ("recurringInvoiceId") REFERENCES "RecurringInvoice"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InvoiceAttachment" ADD CONSTRAINT "InvoiceAttachment_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InvoiceReminder" ADD CONSTRAINT "InvoiceReminder_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QuoteLineItem" ADD CONSTRAINT "QuoteLineItem_quoteId_fkey" FOREIGN KEY ("quoteId") REFERENCES "Quote"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QuoteAttachment" ADD CONSTRAINT "QuoteAttachment_quoteId_fkey" FOREIGN KEY ("quoteId") REFERENCES "Quote"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QuoteReportingTag" ADD CONSTRAINT "QuoteReportingTag_quoteId_fkey" FOREIGN KEY ("quoteId") REFERENCES "Quote"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SalesOrderLineItem" ADD CONSTRAINT "SalesOrderLineItem_salesOrderId_fkey" FOREIGN KEY ("salesOrderId") REFERENCES "SalesOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SalesOrderAttachment" ADD CONSTRAINT "SalesOrderAttachment_salesOrderId_fkey" FOREIGN KEY ("salesOrderId") REFERENCES "SalesOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DeliveryChallanLineItem" ADD CONSTRAINT "DeliveryChallanLineItem_challanId_fkey" FOREIGN KEY ("challanId") REFERENCES "DeliveryChallan"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DeliveryChallanAttachment" ADD CONSTRAINT "DeliveryChallanAttachment_challanId_fkey" FOREIGN KEY ("challanId") REFERENCES "DeliveryChallan"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecurringInvoiceOccurrence" ADD CONSTRAINT "RecurringInvoiceOccurrence_recurringInvoiceId_fkey" FOREIGN KEY ("recurringInvoiceId") REFERENCES "RecurringInvoice"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CreditNoteLineItem" ADD CONSTRAINT "CreditNoteLineItem_creditNoteId_fkey" FOREIGN KEY ("creditNoteId") REFERENCES "CreditNote"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CreditNoteApplication" ADD CONSTRAINT "CreditNoteApplication_creditNoteId_fkey" FOREIGN KEY ("creditNoteId") REFERENCES "CreditNote"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CreditNoteApplication" ADD CONSTRAINT "CreditNoteApplication_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CreditNoteRefund" ADD CONSTRAINT "CreditNoteRefund_creditNoteId_fkey" FOREIGN KEY ("creditNoteId") REFERENCES "CreditNote"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PaymentTerms" ADD CONSTRAINT "PaymentTerms_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DeliveryMethod" ADD CONSTRAINT "DeliveryMethod_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Salesperson" ADD CONSTRAINT "Salesperson_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PdfTemplate" ADD CONSTRAINT "PdfTemplate_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EmailJob" ADD CONSTRAINT "EmailJob_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

